do $$
declare u uuid:=gen_random_uuid(); b uuid; loc uuid; p uuid; other uuid; r jsonb; first uuid; second uuid; third uuid; sid uuid; req uuid:=gen_random_uuid(); day date:=(now() at time zone 'Africa/Johannesburg')::date; blocked boolean; values jsonb; frozen jsonb;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'shifts-fixture@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 r:=public.create_business('Shifts fixture','Till');b:=(r->>'business_id')::uuid;loc:=(r->>'store_id')::uuid;
 p:=public.create_product(loc,'Barcode product','OLD',null,null,5,10);
 other:=public.create_product(loc,'Other product','TAKEN',null,null,5,10);
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',20)));
 values:=jsonb_build_object('name','Barcode product','cost_price',5,'selling_price',10,'min_stock_level',0,'reorder_level',0,'unit','each','track_expiry',false,'is_active',true,'barcode','NEW','expected_barcode','OLD');
 perform public.save_product_details(p,values);
 if (select quantity from public.stock where product_id=p)<>20 or not exists(select 1 from public.product_barcodes where product_id=p and barcode='OLD' and not is_active) or not exists(select 1 from public.product_barcodes where product_id=p and barcode='NEW' and is_active) then raise exception 'ASSERT barcode update preserves stock and old code';end if;
 blocked:=false;begin perform public.save_product_details(p,values||'{"barcode":"STALE"}');exception when others then if sqlerrm<>'BARCODE_CHANGED_REFRESH' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT stale barcode';end if;
 blocked:=false;begin perform public.save_product_details(p,values||'{"barcode":"TAKEN","expected_barcode":"NEW","name":"Wrong"}');exception when others then if sqlerrm<>'BARCODE_ALREADY_EXISTS' then raise;end if;blocked:=true;end;
 if not blocked or (select name from public.products where id=p)<>'Barcode product' then raise exception 'ASSERT duplicate rollback';end if;
 first:=public.open_cash_up(loc,day,100);
 perform public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)));
 r:=public.cash_up_summary(loc,day);sid:=public.submit_cash_up(first,120,'{}',r->>'count_token','',gen_random_uuid());
 blocked:=false;begin perform public.start_next_cash_shift(first,120,'',req);exception when others then if sqlerrm<>'SHIFT_APPROVAL_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT must approve first';end if;
 perform public.review_cash_up(first,sid,'APPROVE','');
 -- A committed payment between count/approval and handover belongs to the next shift.
 perform public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
 second:=public.start_next_cash_shift(first,120,'',req);
 if public.start_next_cash_shift(first,120,'',req)<>second then raise exception 'ASSERT retry creates one shift';end if;
 blocked:=false;begin perform public.start_next_cash_shift(first,120,'',gen_random_uuid());exception when others then if sqlerrm<>'SHIFT_ALREADY_STARTED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT duplicate handover';end if;
 r:=public.cash_up_summary(loc,day);
 if (r->>'expected')::numeric<>130 or (r->'sources'->>'sales')::numeric<>10 or (r->'day_activity'->>'cash_sales')::numeric<>30 then raise exception 'ASSERT delta versus daily totals: %',r;end if;
 frozen:=public.cash_shift_summary(loc,day,first);
 if (frozen->>'expected')::numeric<>120 or (frozen->>'changed_since_count')::boolean or not (frozen->>'sealed')::boolean then raise exception 'ASSERT first frozen';end if;
 blocked:=false;begin perform public.review_cash_up(first,sid,'REOPEN','No overwrite');exception when others then if sqlerrm<>'SHIFT_LOCKED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT no reopen after handover';end if;
 perform public.complete_sale(loc,'CARD_EFT',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),false,null,gen_random_uuid(),'CARD');
 r:=public.cash_up_summary(loc,day);sid:=public.submit_cash_up(second,130,'{}',r->>'count_token','',gen_random_uuid());perform public.review_cash_up(second,sid,'APPROVE','');
 blocked:=false;begin perform public.start_next_cash_shift(second,50,'',gen_random_uuid());exception when others then if sqlerrm<>'HANDOVER_NOTE_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT handover difference explained';end if;
 third:=public.start_next_cash_shift(second,50,'Cash banked before handover',gen_random_uuid());
 r:=public.cash_up_summary(loc,day);
 if (r->>'expected')::numeric<>50 or (r->'sources'->'activity'->>'net_collected')::numeric<>0 or (r->'day_activity'->>'net_collected')::numeric<>40 or jsonb_array_length(r->'shifts')<>3 then raise exception 'ASSERT third shift no double counts: %',r;end if;
 if (public.cash_shift_summary(loc,day,first)->'history')<>(frozen->'history') then raise exception 'ASSERT preserve history';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',gen_random_uuid(),'role','authenticated')::text,true);
 blocked:=false;begin perform public.cash_shift_summary(loc,day,first);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT private shift history';end if;
 blocked:=false;begin perform public.start_next_cash_shift(third,50,'',gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT unauthorized shift start';end if;
 blocked:=false;begin perform public.save_product_details(p,values);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT unauthorized barcode edit';end if;
 raise exception 'TESTS_PASSED';
end $$;
