do $$
declare owner_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); r jsonb; source jsonb; biz uuid; loc uuid; elsewhere uuid; member uuid; product uuid; customer uuid; credit_customer uuid; sale uuid; sale_item uuid; ret uuid; order_id uuid; invoice uuid; day date:=(now() at time zone 'Africa/Johannesburg')::date; cash_up uuid; submission uuid; tid uuid; req uuid; blocked boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(owner_id,'cash-owner@test.invalid','{}'),(staff_id,'cash-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true); set local role authenticated;
 r:=public.create_business('Cash-up test','Cash store'); biz:=(r->>'business_id')::uuid; loc:=(r->>'store_id')::uuid;
 elsewhere:=public.create_location(biz,'Other store','store');
 reset role; member:=public.add_member_by_email(biz,'cash-staff@test.invalid','employee'); set local role authenticated; perform public.set_member_locations(member,array[loc]);
 product:=public.create_product(loc,'Cash test item','CASH-1',null,null,5,10);
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',100)));
 insert into public.customers(business_id,store_id,name) values(biz,loc,'Invoice customer') returning id into customer;
 insert into public.customers(business_id,store_id,name) values(biz,loc,'Credit customer') returning id into credit_customer;
 perform public.set_credit_limit(credit_customer,1000);
 sale:=public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',2)));
 perform public.complete_sale(loc,'CARD_EFT',null,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',1)));
 perform public.complete_sale(loc,'CREDIT',credit_customer,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',10)));
 req:=gen_random_uuid(); tid:=public.record_credit_payment_tender(credit_customer,20,'CASH',req);
 if tid<>public.record_credit_payment_tender(credit_customer,20,'CASH',req) then raise exception 'ASSERT payment retry'; end if;
 perform public.record_credit_payment_tender(credit_customer,10,'CARD_EFT',gen_random_uuid());
 tid:=public.record_credit_payment(credit_customer,10);
 order_id:=public.create_sales_order(loc,customer,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',5)),gen_random_uuid());
 perform public.process_sales_order(order_id,'confirm'); invoice:=public.create_sales_invoice(order_id,day+30,'CASH'); perform public.issue_sales_invoice(invoice);
 perform public.post_invoice_entry(invoice,'PAYMENT',40,gen_random_uuid(),'CASH'); perform public.post_invoice_entry(invoice,'PAYMENT',10,gen_random_uuid(),'CARD_EFT');
 select id into sale_item from public.goods_out_items where goods_out_id=sale;
 ret:=public.submit_goods_return('sale',sale,jsonb_build_array(jsonb_build_object('item_id',sale_item,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 perform public.process_goods_return(ret,true); perform public.record_customer_refund(ret,10,'CASH','Cash refund',gen_random_uuid());
 req:=gen_random_uuid(); perform public.record_cash_movement(loc,day,'ADD',5,'Extra change',req);
 perform public.record_cash_movement(loc,day,'ADD',5,'Extra change',req);
 perform public.record_cash_movement(loc,day,'REMOVE',15,'Bank deposit',gen_random_uuid());
 cash_up:=public.open_cash_up(loc,day,100);
 if cash_up<>public.open_cash_up(loc,day,100) then raise exception 'ASSERT daily opening retry'; end if;
 r:=public.cash_up_summary(loc,day); source:=r->'sources';
 if (source->>'sales')::numeric<>20 or (source->>'invoices')::numeric<>40 or (source->>'credit')::numeric<>20 or (source->>'refunds')::numeric<>10 or (r->>'expected')::numeric<>160 then raise exception 'ASSERT sources and no double count: %',r; end if;
 if jsonb_array_length(source->'unclassified')<>1 then raise exception 'ASSERT unknown historical tender remains visible'; end if;
 blocked:=false; begin perform public.submit_cash_up(cash_up,160,'{}',r->>'count_token','',gen_random_uuid()); exception when others then if sqlerrm<>'UNCLASSIFIED_PAYMENTS' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT unknown tender blocks closing'; end if;
 perform public.classify_credit_payment(tid,'CARD_EFT');
 r:=public.cash_up_summary(loc,day);
 blocked:=false; begin perform public.submit_cash_up(cash_up,160,'{"100":2}',r->>'count_token','',gen_random_uuid()); exception when others then if sqlerrm<>'CASH_COUNT_MISMATCH' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT denominations reconcile'; end if;
 blocked:=false; begin perform public.submit_cash_up(cash_up,159,'{}',r->>'count_token','',gen_random_uuid()); exception when others then if sqlerrm<>'VARIANCE_NOTE_REQUIRED' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT variance explanation required'; end if;
 blocked:=false; begin perform public.open_cash_up(loc,day-1,'NaN'); exception when others then if sqlerrm<>'INVALID_CASH_AMOUNT' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT no non-finite cash'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
 req:=gen_random_uuid(); submission:=public.submit_cash_up(cash_up,159,'{}',r->>'count_token','One rand short',req);
 if submission<>public.submit_cash_up(cash_up,159,'{}',r->>'count_token','One rand short',req) then raise exception 'ASSERT submission retry'; end if;
 blocked:=false; begin perform public.review_cash_up(cash_up,submission,'APPROVE','Reviewed'); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT manager approval required'; end if;
 blocked:=false; begin perform public.cash_up_summary(elsewhere,day); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT cross store cash isolation'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 perform public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',1)));
 blocked:=false; begin perform public.review_cash_up(cash_up,submission,'APPROVE','Reviewed'); exception when others then if sqlerrm<>'CASH_ACTIVITY_CHANGED' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT late payment blocks stale approval'; end if;
 perform public.review_cash_up(cash_up,submission,'REOPEN','New sale arrived');
 r:=public.cash_up_summary(loc,day);
 perform public.correct_cash_up_float(cash_up,110,(r->'session'->>'version')::bigint,'Opening float corrected');
 blocked:=false; begin perform public.submit_cash_up(cash_up,180,'{}',r->>'count_token','',gen_random_uuid()); exception when others then if sqlerrm<>'CASH_ACTIVITY_CHANGED' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT stale opening float detected'; end if;
 r:=public.cash_up_summary(loc,day);
 submission:=public.submit_cash_up(cash_up,180,'{"100":1,"50":1,"20":1,"10":1}',r->>'count_token','Recount',gen_random_uuid());
 perform public.review_cash_up(cash_up,submission,'APPROVE','Recount verified');
 perform public.review_cash_up(cash_up,submission,'APPROVE','Recount verified');
 r:=public.cash_up_summary(loc,day);
 if r->'session'->>'status'<>'APPROVED' or jsonb_array_length(r->'history')<>2 then raise exception 'ASSERT immutable revision history'; end if;
 if (r->'history'->0->>'variance')::numeric<>0 then raise exception 'ASSERT reconciled variance'; end if;
 perform public.record_cash_movement(loc,day,'REMOVE',5,'Late bank deposit',gen_random_uuid());
 r:=public.cash_up_summary(loc,day);
 if not (r->>'changed_since_count')::boolean then raise exception 'ASSERT activity after approval remains flagged'; end if;
 reset role;
 blocked:=false; begin update public.cash_up_submissions set counted=100 where id=submission; exception when others then blocked:=true; end;
 if not blocked then raise exception 'ASSERT submitted count immutable'; end if;
 -- One millisecond before the SA business day belongs to the previous day.
 insert into public.goods_out(business_id,store_id,sale_type,total_amount,created_at) values(biz,loc,'CASH',999,day::timestamp at time zone 'Africa/Johannesburg'-interval '1 millisecond');
 set local role authenticated;
 r:=public.cash_up_summary(loc,day);
 if (r->'sources'->>'sales')::numeric<>30 then raise exception 'ASSERT SA midnight boundary'; end if;
 reset role;
 raise exception 'TESTS_PASSED';
end $$;
