do $$
declare u uuid:=gen_random_uuid(); other_u uuid:=gen_random_uuid(); res jsonb; loc uuid; biz uuid; p uuid; sale uuid; req uuid:=gen_random_uuid(); items jsonb; pays jsonb; bad jsonb; source jsonb; blocked boolean; c uuid; oid uuid; iid uuid;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'checkout@test.invalid','{"full_name":"Original Cashier"}'),(other_u,'checkout-other@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 res:=public.create_business('Checkout test','Shop');loc:=(res->>'store_id')::uuid;biz:=(res->>'business_id')::uuid;
 p:=public.create_product(loc,'Original product','CHECKOUT',null,null,10,100);
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',20)));
 items:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',100));
 pays:='[{"method":"CASH","amount":50},{"method":"CARD","amount":40,"confirmed":true,"reference":"slip"},{"method":"EFT","amount":30,"confirmed":true}]';
 sale:=public.complete_checkout(loc,items,pays,req);
 if sale<>public.complete_checkout(loc,items,pays,req) then raise exception 'ASSERT retry';end if;
 if (select quantity from public.stock where product_id=p)<>19 then raise exception 'ASSERT stock once';end if;
 if (select sum(amount) from public.sale_payments where sale_id=sale)<>100 then raise exception 'ASSERT payment sum';end if;
 if (select amount from public.sale_payments where sale_id=sale and method='CASH')<>30 then raise exception 'ASSERT cash applied';end if;
 if (select (snapshot->>'change')::numeric from public.sale_receipts where sale_id=sale)<>20 then raise exception 'ASSERT change';end if;
 source:=public.cash_up_summary(loc,(now() at time zone 'Africa/Johannesburg')::date);
 if (source->'sources'->>'sales')::numeric<>30 or (source->'sources'->'activity'->>'net_collected')::numeric<>100 then raise exception 'ASSERT cash up %',source;end if;
 foreach bad in array array['[{"method":"CASH","amount":99}]'::jsonb,'[{"method":"CARD","amount":101,"confirmed":true}]','[{"method":"CARD","amount":100}]','[{"method":"CASH","amount":50},{"method":"CASH","amount":50}]','[{"method":"CASH","amount":-1}]','[{"method":"CASH","amount":100.001}]','[{"method":"CASH","amount":"NaN"}]'] loop
  blocked:=false;begin perform public.complete_checkout(loc,items,bad,gen_random_uuid());exception when others then blocked:=true;end;
  if not blocked then raise exception 'ASSERT invalid payment accepted %',bad;end if;
 end loop;
 if (select quantity from public.stock where product_id=p)<>19 or (select count(*) from public.sale_receipts where store_id=loc)<>1 then raise exception 'ASSERT failed payment atomic';end if;
 blocked:=false;begin perform public.complete_checkout(loc,items,'[{"method":"CASH","amount":100}]',req);exception when others then if sqlerrm<>'REQUEST_CONFLICT' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT conflicting retry';end if;
 if (select sum(amount) from public.v_payment_activity where document_id=sale)<>100 or (select count(*) from public.v_payment_activity where document_id=sale)<>3 then raise exception 'ASSERT report split payments';end if;
 perform public.prepare_document_email('sale',sale,gen_random_uuid(),repeat('a',64),'receipt@test.invalid');
 perform public.record_receipt_print(sale,'DECLINED');perform public.record_receipt_print(sale,'REQUESTED');
 if (select count(*) from public.goods_out where id=sale)<>1 or (select quantity from public.stock where product_id=p)<>19 then raise exception 'ASSERT printing changed sale';end if;
 blocked:=false;begin update public.sale_payments set amount=1 where sale_id=sale;exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT mutable payments';end if;
 perform public.save_receipt_preferences(loc,true,4);
 update public.profiles set full_name='Renamed Cashier' where id=u;
 if (select snapshot->>'cashier' from public.sale_receipts where sale_id=sale)<>'Original Cashier' then raise exception 'ASSERT receipt name changed';end if;
 insert into public.customers(business_id,store_id,name) values(biz,loc,'Customer') returning id into c;
 oid:=public.create_sales_order(loc,c,items,gen_random_uuid());perform public.process_sales_order(oid,'confirm');
 update public.profiles set full_name='Invoice Creator' where id=u;
 iid:=public.create_sales_invoice(oid,current_date+1,'CASH',0);
 if (select ordered_by_name from public.sales_orders where id=oid)<>'Renamed Cashier' then raise exception 'ASSERT order snapshot';end if;
 if not exists(select 1 from public.v_invoice_payment_report where id=iid and ordered_by_name='Renamed Cashier' and invoiced_by_name='Invoice Creator') then raise exception 'ASSERT invoice snapshot';end if;
 update public.profiles set full_name='Later name' where id=u;
 if (select invoiced_by_name from public.sales_invoices where id=iid)<>'Invoice Creator' then raise exception 'ASSERT invoice immutable name';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_u,'role','authenticated')::text,true);
 if exists(select 1 from public.sale_receipts where sale_id=sale) or exists(select 1 from public.sale_payments where sale_id=sale) then raise exception 'ASSERT cross tenant read';end if;
 blocked:=false;begin perform public.record_receipt_print(sale,'REQUESTED');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ASSERT cross tenant print';end if;
 if has_function_privilege('anon','public.complete_checkout(uuid,jsonb,jsonb,uuid,uuid,boolean,boolean,uuid,text)','execute') then raise exception 'ASSERT anon checkout';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
