do $$
declare owner_id uuid:=gen_random_uuid(); cashier uuid:=gen_random_uuid(); biz uuid; loc uuid; otherloc uuid; member uuid;
  c uuid; p uuid; res jsonb; token uuid; sale uuid; req uuid:=gen_random_uuid(); payload jsonb; blocked boolean;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(owner_id,'override-owner@test.invalid','{}'),(cashier,'override-cashier@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true); set local role authenticated;
  res:=public.create_business('Override test','Shop'); biz:=(res->>'business_id')::uuid; loc:=(res->>'store_id')::uuid;
  otherloc:=public.create_location(biz,'Other','store');
  reset role; member:=public.add_member_by_email(biz,'override-cashier@test.invalid','employee'); set local role authenticated; perform public.set_member_locations(member,array[loc]);
  perform public.set_credit_override_code(biz,'123456');
  insert into public.customers(business_id,store_id,name) values(biz,loc,'Credit test') returning id into c;
  p:=public.create_product(loc,'Bread','OVERRIDE-BREAD',null,null,5,10);
  perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10)));
  payload:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1));
  perform set_config('request.jwt.claims',jsonb_build_object('sub',cashier,'role','authenticated')::text,true);
  blocked:=false; begin perform public.set_credit_override_code(biz,'987654'); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT cashier cannot configure code'; end if;
  if (select count(*) from public.credit_override_authorizers(loc))<>1 then raise exception 'ASSERT authorized approvers'; end if;
  res:=public.authorize_credit_override(loc,c,owner_id,'000000',10);
  if res->>'error'<>'INVALID_OVERRIDE_CODE' then raise exception 'ASSERT wrong code denied'; end if;
  res:=public.authorize_credit_override(loc,c,owner_id,'123456',10); token:=(res->>'token')::uuid;
  if token is null then raise exception 'ASSERT approval token'; end if;
  sale:=public.complete_sale(loc,'CREDIT',c,payload,false,null,req,null,token);
  if sale<>public.complete_sale(loc,'CREDIT',c,payload,false,null,req,null,token) then raise exception 'ASSERT retry with consumed token'; end if;
  if not exists(select 1 from public.goods_out where id=sale and authorized_by=owner_id and credit_override) then raise exception 'ASSERT real approving manager recorded'; end if;
  blocked:=false; begin perform public.complete_sale(loc,'CREDIT',c,payload,false,null,gen_random_uuid(),null,token); exception when others then if sqlerrm<>'OVERRIDE_NOT_AUTHORIZED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT token single use'; end if;
  res:=public.authorize_credit_override(loc,c,owner_id,'123456',5); token:=(res->>'token')::uuid;
  blocked:=false; begin perform public.complete_sale(loc,'CREDIT',c,payload,false,null,gen_random_uuid(),null,token); exception when others then if sqlerrm<>'OVERRIDE_NOT_AUTHORIZED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT approval amount cannot increase'; end if;
  for i in 1..5 loop res:=public.authorize_credit_override(loc,c,owner_id,'000000',10); end loop;
  res:=public.authorize_credit_override(loc,c,owner_id,'123456',10);
  if res->>'error'<>'OVERRIDE_RATE_LIMITED' then raise exception 'ASSERT brute force limited'; end if;
  blocked:=false; begin perform public.authorize_credit_override(otherloc,c,owner_id,'123456',10); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT location denial'; end if;
  if exists(select 1 from public.reconcile_stock(loc) where diff<>0) then raise exception 'ASSERT failed approvals leave stock reconciled'; end if;
  if (select balance from public.credit_accounts where customer_id=c)<>10 then raise exception 'ASSERT debt recorded once'; end if;
  reset role; raise exception 'TESTS_PASSED';
end $$;
