do $$
declare u uuid:=gen_random_uuid();outside_user uuid:=gen_random_uuid();b uuid;s uuid;c uuid;p uuid;o uuid;i uuid;d uuid;q uuid;sale uuid;r uuid;line uuid;req uuid;job uuid;x jsonb;y jsonb;n int;blocked boolean;today date:=current_date;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'customer-mail@test.invalid','{}'),(outside_user,'customer-mail-out@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 x:=public.create_business('Email business','Email shop');b:=(x->>'business_id')::uuid;s:=(x->>'store_id')::uuid;
 insert into public.customers(business_id,store_id,name,email,email_notifications,credit_enabled) values(b,s,'Email Customer','customer@example.test',true,true) returning id into c;
 perform public.set_credit_limit(c,1000);
 p:=public.create_product(s,'Email parcel','EMAIL-TEST',null,null,5,10);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',100)));
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),gen_random_uuid());
 set constraints all immediate;set constraints all deferred;
 if exists(select 1 from public.customer_document_notifications where customer_id=c) then raise exception 'ASSERT drafts not queued';end if;
 perform public.configure_order_delivery(o,0,true,jsonb_build_object('date',today,'address','10 Road','phone','0123456'));
 perform public.process_sales_order(o,'confirm');i:=public.create_sales_invoice(o,today+1,'CASH',0,null);perform public.issue_sales_invoice(i);
 req:=gen_random_uuid();perform public.post_invoice_entry(i,'PAYMENT',20,req,'CASH');perform public.post_invoice_entry(i,'PAYMENT',20,req,'CASH');perform public.issue_invoice_goods(i);
 select id into d from public.order_deliveries where invoice_id=i;
 perform public.process_delivery(d,1,'dispatch','{}',gen_random_uuid());perform public.process_delivery(d,2,'complete','{"received_by":"Email Receiver"}',gen_random_uuid());
 set constraints all immediate;set constraints all deferred;
 if (select count(*) from public.recurring_invoice_deliveries where invoice_id=i)<>1 then raise exception 'ASSERT general opt-in queues exactly one invoice';end if;
 if (select count(*) from public.customer_document_notifications where customer_id=c and document->>'type'='Payment receipt')<>1 then raise exception 'ASSERT payment retry duplicates';end if;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Order confirmation' and jsonb_array_length(document->'lines')=1 and (document->>'total')::numeric=20) then raise exception 'ASSERT order lines complete at commit';end if;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Delivery note' and document->'details'->>'Received by'='Email Receiver') then raise exception 'ASSERT delivered document';end if;
 if (select count(*) from public.customer_document_notifications where customer_id=c and document->>'type'='Delivery note')<>3 then raise exception 'ASSERT delivery events';end if;
 sale:=public.complete_checkout(s,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10)),'[{"method":"CASH","amount":15}]',gen_random_uuid(),c);
 select id into line from public.sales_invoice_items where invoice_id=i;
 r:=public.submit_goods_return('invoice',i,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Inspected',gen_random_uuid());perform public.process_goods_return(r,true);
 perform public.record_customer_refund(r,10,'CASH','Refund',gen_random_uuid());
 q:=public.save_quote(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),today+7,0,'Offer',gen_random_uuid());perform public.set_quote_status(q,'SENT',1);
 set constraints all immediate;set constraints all deferred;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Goods Out / sales receipt' and (document->'details'->>'Change')::numeric=5 and (document->>'total')::numeric=10) then raise exception 'ASSERT checkout receipt total and change';end if;
 if (select count(*) from public.customer_document_notifications where customer_id=c and document->>'type' in ('Return / credit note','Credit note'))<>1 then raise exception 'ASSERT return credit duplicate';end if;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Refund receipt') or not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Quotation') then raise exception 'ASSERT refund quote coverage';end if;
 perform public.complete_checkout(s,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10)),'[]',gen_random_uuid(),c,true);
 perform public.record_credit_payment_tender(c,5,'CASH',gen_random_uuid(),'Part payment');
 set constraints all immediate;set constraints all deferred;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Account payment receipt') then raise exception 'ASSERT standalone account payment';end if;
 req:=gen_random_uuid();job:=public.queue_customer_statement(c,req,today-1,today);
 if job is distinct from public.queue_customer_statement(c,req,today-1,today) then raise exception 'ASSERT statement idempotency';end if;
 if not exists(select 1 from public.customer_document_notifications where id=job and (document->>'outstanding')::numeric=5 and jsonb_array_length(document->'lines')>0) then raise exception 'ASSERT full statement';end if;
 blocked:=false;begin perform public.queue_customer_statement(c,req,today-2,today);exception when others then if sqlerrm<>'REQUEST_CHANGED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT statement conflicting retry';end if;
 if jsonb_array_length(public.customer_email_history(c))<10 then raise exception 'ASSERT history includes documents';end if;
 -- Worker role only, fail closed with current customer consent, recipient and author access.
 blocked:=false;begin perform public.claim_customer_documents();exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'ASSERT worker cannot be called by customer actor';end if;
 reset role;perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 x:=public.claim_customer_documents(5);if jsonb_array_length(x)<>5 then raise exception 'ASSERT bounded claim';end if;
 y:=public.claim_customer_documents(5);
 if exists(select 1 from jsonb_array_elements(x) a join jsonb_array_elements(y) z on a->>'id'=z->>'id') then raise exception 'ASSERT no duplicate claims';end if;
 perform public.complete_customer_document((x->0->>'id')::uuid,(x->0->>'token')::uuid,'SENT','provider-id');
 perform public.complete_customer_document((x->1->>'id')::uuid,(x->1->>'token')::uuid,'PREPARATION_FAILED');
 perform public.complete_customer_document((x->2->>'id')::uuid,(x->2->>'token')::uuid,'UNCERTAIN');
 if not exists(select 1 from public.customer_document_notifications where id=(x->1->>'id')::uuid and state='PENDING' and available_at>now()) then raise exception 'ASSERT preparation retry delay';end if;
 if not exists(select 1 from public.customer_document_notifications where id=(x->2->>'id')::uuid and state='UNCERTAIN') then raise exception 'ASSERT uncertain never automatically retried';end if;
 blocked:=false;begin perform public.complete_customer_document((x->0->>'id')::uuid,gen_random_uuid(),'SENT','wrong');exception when others then if sqlerrm<>'INVALID_RESERVATION' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT token protection';end if;
 update public.customers set email_notifications=false where id=c;
 update public.customer_document_notifications set available_at=now() where customer_id=c and state='PENDING';
 perform public.claim_customer_documents(5);perform public.claim_recurring_deliveries(10);
 if exists(select 1 from public.customer_document_notifications where customer_id=c and state='PENDING') then raise exception 'ASSERT opt-out pending jobs';end if;
 if (select state from public.recurring_invoice_deliveries where invoice_id=i)<>'FAILED' then raise exception 'ASSERT invoice consent revocation';end if;
 update public.customers set email_notifications=true where id=c;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 job:=public.queue_customer_statement(c,gen_random_uuid(),today-1,today);
 reset role;update public.customers set email='changed@example.test' where id=c;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);perform public.claim_customer_documents(5);
 if (select state from public.customer_document_notifications where id=job)<>'SKIPPED' then raise exception 'ASSERT changed recipient stops queued mail';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 job:=public.queue_customer_statement(c,gen_random_uuid(),today-1,today);
 reset role;
 update public.memberships set role='employee' where business_id=b and user_id=u;
 insert into public.store_memberships(membership_id,store_id,business_id) select id,s,b from public.memberships where user_id=u and business_id=b on conflict do nothing;
 insert into public.store_module_access(membership_id,store_id,permissions) select id,s,'{"credit":false}'::jsonb from public.memberships where user_id=u and business_id=b on conflict(membership_id,store_id) do update set permissions=excluded.permissions;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);perform public.claim_customer_documents(5);
 if (select state from public.customer_document_notifications where id=job)<>'SKIPPED' then raise exception 'ASSERT revoked module stops queued mail';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outside_user,'role','authenticated')::text,true);set local role authenticated;
 if exists(select 1 from public.customer_document_notifications where customer_id=c) then raise exception 'ASSERT cross tenant RLS';end if;
 blocked:=false;begin perform public.customer_email_history(c);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cross tenant history';end if;
 blocked:=false;begin perform public.queue_customer_statement(c,gen_random_uuid(),today-1,today);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cross tenant statement';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
