do $$
declare u uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();b uuid;s uuid;c uuid;p uuid;o uuid;i uuid;d uuid;x jsonb;v bigint;req uuid;blocked boolean;date0 date:=current_date;num int;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'delivery@test.invalid','{}'),(outsider,'delivery-outside@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 x:=public.create_business('Delivery business','Delivery store');b:=(x->>'business_id')::uuid;s:=(x->>'store_id')::uuid;
 insert into public.customers(business_id,store_id,name,phone,address) values(b,s,'Receiver','0112345678','10 Main Road') returning id into c;
 p:=public.create_product(s,'Parcel','DELIVERY-TEST',null,null,5,10);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',20)));
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),gen_random_uuid());
 perform public.configure_order_delivery(o,0,true,jsonb_build_object('date',date0,'address','10 Main Road','phone','0112345678'));
 x:=public.order_workflow_summary(s);if x->0->>'status'<>'DRAFT' then raise exception 'ASSERT delivery setting must not hide confirm-order action';end if;
 perform public.process_sales_order(o,'confirm');i:=public.create_sales_invoice(o,current_date+1,'CASH',0,null);
 perform public.issue_sales_invoice(i);
 if exists(select 1 from public.order_deliveries where invoice_id=i) then raise exception 'ASSERT no note until paid';end if;
 perform public.post_invoice_entry(i,'PAYMENT',10,gen_random_uuid(),'CASH');
 if exists(select 1 from public.order_deliveries where invoice_id=i) then raise exception 'ASSERT no partial payment note';end if;
 req:=gen_random_uuid();perform public.post_invoice_entry(i,'PAYMENT',10,req,'CASH');perform public.post_invoice_entry(i,'PAYMENT',10,req,'CASH');
 select id,version into d,v from public.order_deliveries where invoice_id=i;
 if d is null or (select count(*) from public.order_deliveries where invoice_id=i)<>1 then raise exception 'ASSERT exactly one automatic note';end if;
 if public.order_workflow_summary(s)->0->>'status'<>'PENDING_DELIVERY' then raise exception 'ASSERT paid order stays delivery pending';end if;
 blocked:=false;begin perform public.process_delivery(d,v,'dispatch','{}',gen_random_uuid());exception when others then if sqlerrm<>'DELIVERY_RELEASE_GOODS_FIRST' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT release required';end if;
 perform public.issue_invoice_goods(i);
 if public.order_workflow_summary(s)->0->>'status'<>'PENDING_DELIVERY' then raise exception 'ASSERT released order not completed';end if;
 perform public.process_delivery(d,v,'update','{"address":"10 Main Road","phone":"0112345678","driver_name":"Driver One","vehicle_registration":"ABC123GP","remarks":{}}',gen_random_uuid());v:=v+1;
 req:=gen_random_uuid();perform public.process_delivery(d,v,'dispatch','{}',req);perform public.process_delivery(d,v,'dispatch','{}',req);v:=v+1;
 perform public.process_delivery(d,v,'fail','{"notes":"Customer unavailable"}',gen_random_uuid());v:=v+1;
 perform public.process_delivery(d,v,'reschedule',jsonb_build_object('date',date0+1,'notes','Agreed tomorrow'),gen_random_uuid());v:=v+1;
 if jsonb_array_length(public.delivery_page(s,'current')->'rows')<>0 or jsonb_array_length(public.delivery_page(s,'scheduled')->'rows')<>1 then raise exception 'ASSERT rescheduled queue isolation';end if;
 if (public.delivery_detail(o)->'delivery'->>'original_date')::date<>date0 or (public.delivery_detail(o)->'delivery'->>'scheduled_date')::date<>date0+1 then raise exception 'ASSERT original and revised note dates';end if;
 blocked:=false;begin perform public.process_delivery(d,v-1,'dispatch','{}',gen_random_uuid());exception when others then if sqlerrm<>'DELIVERY_CHANGED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT stale actions';end if;
 perform public.process_delivery(d,v,'dispatch','{}',gen_random_uuid());v:=v+1;
 if jsonb_array_length(public.delivery_page(s,'current')->'rows')<>1 then raise exception 'ASSERT early dispatched delivery remains in current queue';end if;
 blocked:=false;begin perform public.process_delivery(d,v,'complete','{}',gen_random_uuid());exception when others then if sqlerrm<>'DELIVERY_RECIPIENT_REQUIRED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT receiver required';end if;
 perform public.process_delivery(d,v,'complete','{"received_by":"Customer Person","receiver_phone":"0112345678","notes":"All goods accepted"}',gen_random_uuid());
 if public.order_workflow_summary(s)->0->>'status'<>'COMPLETED' then raise exception 'ASSERT delivered completes order';end if;
 if not exists(select 1 from public.order_deliveries where id=d and status='DELIVERED' and confirmed_by=u and delivered_at is not null and received_by='Customer Person') then raise exception 'ASSERT proof details';end if;
 if (select count(*) from public.delivery_events where delivery_id=d)<>7 then raise exception 'ASSERT history includes each change exactly once';end if;
 if (select quantity from public.stock where product_id=p)<>18 then raise exception 'ASSERT stock deducted once';end if;
 -- A delivery requirement added after payment also generates its note immediately.
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),gen_random_uuid());perform public.process_sales_order(o,'confirm');i:=public.create_sales_invoice(o,current_date+1,'CASH',0,null);perform public.issue_sales_invoice(i);perform public.post_invoice_entry(i,'PAYMENT',10,gen_random_uuid(),'CASH');
 d:=public.configure_order_delivery(o,0,true,jsonb_build_object('date',date0,'address','10 Main Road','phone','0112345678'));v:=1;
 if d is null then raise exception 'ASSERT requirement after payment';end if;
 blocked:=false;begin perform public.process_delivery(d,v,'cancel_order','{"reason":"Other"}',gen_random_uuid());exception when others then if sqlerrm<>'DELIVERY_CANCELLATION_REASON_REQUIRED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT other explanation';end if;
 perform public.process_delivery(d,v,'cancel_order','{"reason":"Customer Cancelled Order","notes":"Refund to be arranged"}',gen_random_uuid());
 if (select status from public.sales_orders where id=o)<>'CANCELLED' or (select status from public.order_deliveries where id=d)<>'CANCELLED' then raise exception 'ASSERT cancellation linked';end if;
 if jsonb_array_length(public.delivery_page(s,'current')->'rows')<>0 or jsonb_array_length(public.delivery_page(s,'scheduled')->'rows')<>0 or jsonb_array_length(public.delivery_page(s,'cancelled')->'rows')<>1 then raise exception 'ASSERT cancelled not outstanding';end if;
 if (select paid from public.v_invoice_balances where id=i)<>10 or (select quantity from public.stock where product_id=p)<>18 then raise exception 'ASSERT cancellation leaves money and stock';end if;
 blocked:=false;begin perform public.issue_invoice_goods(i);exception when others then if sqlerrm<>'ORDER_CANCELLED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cannot release cancelled order';end if;
 -- Revocation applies to reads, rows and retries immediately, in the same business.
 reset role;
 update public.memberships set role='employee' where user_id=u and business_id=b;
 insert into public.store_memberships(membership_id,store_id,business_id) select id,s,b from public.memberships where user_id=u and business_id=b on conflict do nothing;
 insert into public.store_module_access(membership_id,store_id,permissions) select id,s,'{"orders_deliveries":false}'::jsonb from public.memberships where user_id=u and business_id=b on conflict(membership_id,store_id) do update set permissions=excluded.permissions;
 set local role authenticated;
 blocked:=false;begin perform public.delivery_detail(o);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT module revocation detail';end if;
 blocked:=false;begin perform public.process_delivery(d,v,'cancel','{"reason":"Other","notes":"Denied"}',gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT module revocation action';end if;
 if exists(select 1 from public.order_deliveries) or exists(select 1 from public.delivery_events) then raise exception 'ASSERT module revocation RLS';end if;
 reset role;perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.delivery_detail(o);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT tenant detail isolation';end if;
 if exists(select 1 from public.order_deliveries) or exists(select 1 from public.delivery_events) then raise exception 'ASSERT RLS isolation';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
