do $$
 declare u uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); biz uuid; loc uuid; otherloc uuid; c uuid; p uuid; p2 uuid; member uuid; res jsonb; qid uuid; oid uuid; iid uuid; rid uuid; line uuid; req uuid:=gen_random_uuid(); items jsonb; result jsonb; blocked boolean; po uuid; n integer;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'document-owner@test.invalid','{}'),(employee,'document-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 res:=public.create_business('Document workflows','Shop');biz:=(res->>'business_id')::uuid;loc:=(res->>'store_id')::uuid;
 reset role; member:=public.add_member_by_email(biz,'document-staff@test.invalid','employee'); set local role authenticated;perform public.set_member_locations(member,array[loc]);
 insert into public.customers(business_id,store_id,name) values(biz,loc,'Quote customer') returning id into c;
 p:=public.create_product(loc,'In stock water','DOC-WATER',null,null,5,10,0,0,'each',false);
 p2:=public.create_product(loc,'Unavailable water','DOC-NONE',null,null,5,17,0,0,'each',false);
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10)));
 perform public.set_billing_settings(biz,15,true);
 items:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',4,'unit_price',10),jsonb_build_object('product_id',p2,'quantity',1,'unit_price',17));
 qid:=public.save_quote(loc,c,items,current_date+30,5.7,'Original quote',req);
 if qid<>public.save_quote(loc,c,items,current_date+30,5.7,'Original quote',req) then raise exception 'ASSERT quote retry'; end if;
 if (select total from public.sales_quotes where id=qid)<>59 then raise exception 'ASSERT quote total'; end if;
 if (select quantity from public.stock where product_id=p)<>10 or (select balance from public.credit_accounts where customer_id=c)<>0 then raise exception 'ASSERT quote has no stock/debt impact'; end if;
 perform public.save_quote(loc,c,items,current_date+30,5.7,'Revised draft',gen_random_uuid(),qid,1);
 blocked:=false;begin perform public.save_quote(loc,c,items,current_date+30,5.7,'Stale draft',gen_random_uuid(),qid,1);exception when others then if sqlerrm<>'QUOTE_CHANGED_REFRESH' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT stale edit rejected';end if;
 perform public.save_purchase_order(qid,null,true,true,'PO-TEST','po.pdf','application/pdf',encode(convert_to('%PDF-test','UTF8'),'base64'),0);
 select id into po from public.sales_purchase_orders where quote_id=qid;
 result:=public.download_purchase_order(po);
 if result->>'filename'<>'po.pdf' then raise exception 'ASSERT PO download';end if;
 perform public.set_quote_status(qid,'SENT',2);
 blocked:=false;begin perform public.convert_quote(qid,jsonb_build_array(jsonb_build_object('product_id',p2,'quantity',1)),3);exception when others then if sqlerrm<>'QUOTE_STOCK_CHANGED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT unavailable conversion rejected';end if;
 items:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2));
 oid:=public.convert_quote(qid,items,3);
 if oid<>public.convert_quote(qid,items,3) then raise exception 'ASSERT conversion retry';end if;
 blocked:=false;begin perform public.convert_quote(qid,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),3);exception when others then if sqlerrm<>'QUOTE_ALREADY_CONVERTED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT different conversion cannot create second order';end if;
 if (select count(*) from public.sales_orders where id=oid)<>1 or (select quantity from public.stock where product_id=p)<>10 then raise exception 'ASSERT conversion no reservation';end if;
 if (select order_id from public.sales_purchase_orders where id=po)<>oid then raise exception 'ASSERT PO follows conversion';end if;
 perform public.set_billing_settings(biz,0,true);
 perform public.process_sales_order(oid,'confirm');iid:=public.create_sales_invoice(oid,current_date+30,'CASH');
 if (select total from public.sales_invoices where id=iid)<>20.7 or (select tax_percent from public.sales_invoices where id=iid)<>15 then raise exception 'ASSERT quote terms preserved';end if;
 perform public.issue_sales_invoice(iid);perform public.post_invoice_entry(iid,'PAYMENT',20.7,gen_random_uuid(),'CASH','PAY-TEST');perform public.issue_invoice_goods(iid);
 select id into line from public.sales_invoice_items where invoice_id=iid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 rid:=public.submit_goods_return('invoice',iid,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','EXPIRED','action','WRITE_OFF')),'Expired','Inspected',gen_random_uuid());
 blocked:=false;begin perform public.process_goods_return(rid,true);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT employee needs delegation';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 perform public.set_store_return_access(member,loc,true,false,0);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 perform public.process_goods_return(rid,true);
 result:=public.return_refund_summary(rid);
 if (result->>'available')::numeric<>10.35 or result->>'reference'<>'PAY-TEST' then raise exception 'ASSERT original net amount and reference';end if;
 blocked:=false;begin perform public.record_customer_refund(rid,1,'CASH','Refund',gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT approval does not grant refunds';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 perform public.set_store_return_access(member,loc,true,true,1);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 perform public.record_customer_refund(rid,5,'CASH','Partial refund',gen_random_uuid());
 if (public.return_refund_summary(rid)->>'available')::numeric<>5.35 then raise exception 'ASSERT partial balance';end if;
 perform public.record_customer_refund(rid,5.35,'CASH','Final refund',gen_random_uuid());
 if (public.return_refund_summary(rid)->>'available')::numeric<>0 then raise exception 'ASSERT complete balance';end if;
 blocked:=false;begin perform public.record_customer_refund(rid,1,'CASH','Excess',gen_random_uuid());exception when others then if sqlerrm<>'REFUND_EXCEEDS_AVAILABLE_CREDIT' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT complete cap';end if;
 result:=public.stock_export(loc,'out','Unavailable');
 if jsonb_array_length(result)<>1 or result->0->>'name'<>'Unavailable water' then raise exception 'ASSERT filtered export';end if;
 if jsonb_array_length(public.stock_export(loc,'ok','Unavailable'))<>0 then raise exception 'ASSERT stock status combined search';end if;
 blocked:=false;begin perform public.stock_export(gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT cross-store export';end if;
 blocked:=false;begin perform public.set_store_return_access(member,loc,true,true,2);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT employee cannot delegate';end if;
 blocked:=false;begin perform public.save_purchase_order(qid,null,false,false,'Changed',null,null,null,1);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT employee cannot change approved PO';end if;
 blocked:=false;begin perform content from public.sales_purchase_orders where id=po;exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT file content requires download RPC';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 oid:=public.complete_sale(loc,'CARD_EFT',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),false,null,gen_random_uuid(),'CARD-ORIGINAL');
 select id into line from public.goods_out_items where goods_out_id=oid;
 rid:=public.submit_goods_return('sale',oid,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 if public.return_refund_summary(rid)->>'reference'<>'CARD-ORIGINAL' then raise exception 'ASSERT checkout payment reference';end if;
 for n in 1..24 loop perform public.create_product(loc,'Export test '||n,'EXP-'||n,null,null,1,2,0,0,'each',false);end loop;
 if jsonb_array_length(public.stock_export(loc,'out','Export test'))<>24 then raise exception 'ASSERT all matching exports exceed screen page size';end if;
 blocked:=false;begin perform public.save_quote(loc,c,items,current_date-1,0,'Expired',gen_random_uuid());exception when others then if sqlerrm<>'QUOTE_VALIDITY_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT invalid validity';end if;
 perform public.set_store_module_access(member,loc,'{"returns":false,"invoices":false,"check_stock":false}',0);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 if (public.my_module_access(loc)->>'returns')::boolean then raise exception 'ASSERT module revoked';end if;
 blocked:=false;begin perform public.process_goods_return(rid,true);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT delegation respects module';end if;
 if exists(select 1 from public.sales_quotes where id=qid) then raise exception 'ASSERT quote RLS';end if;
 blocked:=false;begin perform public.stock_export(loc);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT stock export module';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 qid:=public.save_quote(loc,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),current_date+30,0,'No PO required',gen_random_uuid());
 oid:=public.convert_quote(qid,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),1);
 perform public.save_purchase_order(null,oid,true,false,'LATE-PO',null,null,null,1);
 if (select reference from public.sales_purchase_orders where quote_id=qid)<>'LATE-PO' then raise exception 'ASSERT PO added after conversion stays linked';end if;
 raise exception 'TESTS_PASSED';
end $$;
