do $$
declare owner_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); biz uuid; shop uuid; second uuid; other uuid; invited uuid; req uuid:=gen_random_uuid(); mid uuid; ctx jsonb; res jsonb; assignments jsonb; blocked boolean; saved_version bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at,encrypted_password) values(owner_id,'invite-owner@test.invalid','{}',now(),'test-password'),(stranger,'invite-stranger@test.invalid','{}',now(),'test-password');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);set local role authenticated;
 res:=public.create_business('Invitation test','First shop');biz:=(res->>'business_id')::uuid;shop:=(res->>'store_id')::uuid;
 reset role;
 insert into public.stores(business_id,name) values(biz,'Second shop') returning id into second;
 insert into public.stores(business_id,name) values(biz,'Temporary shop') returning id into other;
 set local role authenticated;
 blocked:=false;begin perform public.add_member_by_email(biz,'invite-stranger@test.invalid','employee');exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT legacy membership admission blocked';end if;
 blocked:=false;begin insert into public.memberships(business_id,user_id,role,is_active) values(biz,stranger,'employee',true);exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT direct membership admission blocked';end if;
 blocked:=false;begin update public.memberships set user_id=stranger where business_id=biz and user_id=owner_id;exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT membership identity replacement blocked';end if;
 assignments:=jsonb_build_object(shop,jsonb_build_object('goods_out',true),second,jsonb_build_object('check_stock',true));
 invited:=public.save_employee_invitation(biz,'invite-staff@test.invalid','employee',assignments,req);
 if invited<>public.save_employee_invitation(biz,'invite-staff@test.invalid','employee',assignments,req) then raise exception 'ASSERT creation retry'; end if;
 if exists(select 1 from public.memberships where business_id=biz and user_id=staff_id) then raise exception 'ASSERT pending has no membership'; end if;
 blocked:=false;begin perform public.save_employee_invitation(biz,'other@test.invalid','employee',jsonb_build_object(shop,jsonb_build_object('users',true)),gen_random_uuid()); exception when others then if sqlerrm<>'INVALID_MODULE_ACCESS' then raise; end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT role cap';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',stranger,'role','authenticated')::text,true);
 if exists(select 1 from public.employee_invitations where id=invited) then raise exception 'ASSERT invitation RLS';end if;
 blocked:=false;begin perform public.save_employee_invitation(biz,'other@test.invalid','employee',assignments,gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT unauthorized invite';end if;
 blocked:=false;begin perform public.prepare_employee_invitation_delivery(owner_id,invited,1);exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ASSERT no caller can obtain auth links';end if;
 reset role;
 ctx:=public.prepare_employee_invitation_delivery(owner_id,invited,1);
 insert into auth.users(id,email,raw_user_meta_data) values(staff_id,'invite-staff@test.invalid','{}');
 perform public.finish_employee_invitation_delivery(invited,(ctx->>'version')::bigint,staff_id,true);
 blocked:=false;begin update auth.users set email_change='changed@test.invalid' where id=staff_id;exception when others then if sqlerrm<>'EMAIL_MANAGED_BY_EMPLOYER' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT direct auth email-change request';end if;
 blocked:=false;begin update auth.users set email='changed@test.invalid' where id=staff_id;exception when others then if sqlerrm<>'EMAIL_MANAGED_BY_EMPLOYER' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT direct auth email change';end if;
 blocked:=false;begin insert into public.memberships(business_id,user_id,role) values(biz,staff_id,'employee');exception when others then if sqlerrm<>'EMPLOYEE_SETUP_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT incomplete identity cannot get active access';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.create_business('Bypass','Shop');exception when others then if sqlerrm<>'INVITATION_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT employee cannot bootstrap owner';end if;
 blocked:=false;begin perform public.employee_invitation_details(invited,ctx->>'secret');exception when others then if sqlerrm<>'INVITATION_INVALID' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT unverified identity';end if;
 reset role;update auth.users set email_confirmed_at=now() where id=staff_id;set local role authenticated;
 blocked:=false;begin perform public.accept_employee_invitation(invited,ctx->>'secret','First','Surname','0711234567');exception when others then if sqlerrm<>'PASSWORD_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT password required';end if;
 reset role;update auth.users set encrypted_password='chosen-by-user' where id=staff_id;set local role authenticated;
 perform public.accept_employee_invitation(invited,ctx->>'secret','First','Surname','0711234567');
 perform public.accept_employee_invitation(invited,ctx->>'secret','First','Surname','0711234567');
 if (select count(*) from public.memberships where business_id=biz and user_id=staff_id)<>1 then raise exception 'ASSERT one membership on retry';end if;
 if not (public.my_module_access(shop)->>'goods_out')::boolean or (public.my_module_access(shop)->>'check_stock')::boolean or not (public.my_module_access(second)->>'check_stock')::boolean or (public.my_module_access(second)->>'goods_out')::boolean then raise exception 'ASSERT per-store deny-by-default grants';end if;
 if exists(select 1 from public.stores where id=other) then raise exception 'ASSERT no unassigned store';end if;
 if (select full_name from public.profiles where id=staff_id)<>'First Surname' then raise exception 'ASSERT profile';end if;
 if (public.my_employee_setup()->>'required')::boolean then raise exception 'ASSERT setup complete';end if;
 reset role;perform public.set_registration_open(false);
 blocked:=false;begin insert into auth.users(id,email) values(gen_random_uuid(),'uninvited@test.invalid');exception when others then if sqlerrm<>'REGISTRATION_CLOSED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT direct registration closed';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.create_business('Closed bypass','Shop');exception when others then if sqlerrm<>'INVITATION_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT closed business bootstrap';end if;
 invited:=public.save_employee_invitation(biz,'invite-new@test.invalid','employee',assignments,gen_random_uuid());
 reset role;insert into auth.users(id,email) values(gen_random_uuid(),'invite-new@test.invalid');
 ctx:=public.prepare_employee_invitation_delivery(owner_id,invited,1);
 saved_version:=(ctx->>'version')::bigint;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);set local role authenticated;
 perform public.cancel_employee_invitation(invited,saved_version);
 reset role;
 select id into staff_id from auth.users where email='invite-new@test.invalid';update auth.users set email_confirmed_at=now(),encrypted_password='chosen' where id=staff_id;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.accept_employee_invitation(invited,ctx->>'secret','First','Surname','0711234567');exception when others then if sqlerrm<>'INVITATION_INVALID' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT cancelled token';end if;
 reset role;
 perform public.set_registration_open(true);
 -- Existing users retain their own account until acceptance; no password reset.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);set local role authenticated;
 invited:=public.save_employee_invitation(biz,'invite-stranger@test.invalid','employee',assignments,gen_random_uuid());
 reset role;ctx:=public.prepare_employee_invitation_delivery(owner_id,invited,1);
 if exists(select 1 from app.managed_identities where user_id=stranger) then raise exception 'ASSERT pending invitation cannot lock an existing identity';end if;
 -- Resend rotates the acceptance secret and invalidates the previous link.
 update public.employee_invitations set sent_at=now()-interval '2 minutes' where id=invited;
 res:=public.prepare_employee_invitation_delivery(owner_id,invited,(ctx->>'version')::bigint);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',stranger,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.employee_invitation_details(invited,ctx->>'secret');exception when others then if sqlerrm<>'INVITATION_INVALID' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT previous link revoked on resend';end if;
 reset role;update public.employee_invitations set expires_at=now()-interval '1 second' where id=invited;set local role authenticated;
 blocked:=false;begin perform public.employee_invitation_details(invited,res->>'secret');exception when others then if sqlerrm<>'INVITATION_EXPIRED_OR_CANCELLED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT expired link';end if;
 reset role;update public.employee_invitations set expires_at=now()+interval '1 day' where id=invited;set local role authenticated;
 perform public.accept_employee_invitation(invited,res->>'secret','Existing','Person','0711234567');
 reset role;
 if (select encrypted_password from auth.users where id=stranger)<>'test-password' then raise exception 'ASSERT existing password retained';end if;
 raise exception 'TESTS_PASSED';
end $$;
