do $$
declare owner_id uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); b uuid; s uuid; other_store uuid;
 membership uuid; p uuid; p2 uuid; take uuid; item uuid; result jsonb; template jsonb; rows jsonb; export_id uuid:=gen_random_uuid();
 before_qty numeric; v bigint:=0;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(owner_id,'excel-owner@test.invalid','{}'),(employee,'excel-employee@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);set local role authenticated;
 result:=public.create_business('Excel permissions','First shop');b:=(result->>'business_id')::uuid;s:=(result->>'store_id')::uuid;
 other_store:=public.create_location(b,'Other shop','store',null);
 p:=public.create_product(s,'Product A',null,null,null,5,10);p2:=public.create_product(s,'Product B',null,null,null,2,7);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',100,'unit_cost',5),jsonb_build_object('product_id',p2,'quantity',50,'unit_cost',2)));
 reset role;membership:=public.add_member_by_email(b,'excel-employee@test.invalid','employee');set local role authenticated;
 perform public.set_member_locations(membership,array[s,other_store]);
 v:=public.set_store_module_access(membership,s,'{"goods_in_new_stock":true}',v);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 if app.has_module(s,'goods_out_change_price') or app.has_module(s,'invoices_summary') then raise exception 'ASSERT employee defaults';end if;
 begin perform public.complete_sale(s,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',9)));raise exception 'ASSERT employee discount denied';exception when others then if sqlerrm<>'PRICE_CHANGE_NOT_ALLOWED' then raise;end if;end;
 perform public.complete_sale(s,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10)));
 begin perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_cost',3)));raise exception 'ASSERT employee cost edit denied';exception when others then if sqlerrm<>'UNIT_COST_CHANGE_NOT_ALLOWED' then raise;end if;end;
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_cost',5)));
 if (select cost_price from public.products where id=p)<>5 then raise exception 'ASSERT employee cost preserved';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 v:=public.set_store_module_access(membership,s,'{"goods_in_new_stock":true,"goods_out_change_price":true}',v);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 perform public.complete_sale(s,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',9)));
 if app.has_module(other_store,'goods_out_change_price') then raise exception 'ASSERT price grant scoped to store';end if;
 template:=public.export_stock_take_template(s,export_id);take:=(template->>'stock_take_id')::uuid;
 if jsonb_array_length(template->'items')<>2 then raise exception 'ASSERT all store products exported';end if;
 if public.export_stock_take_template(s,export_id)<>template then raise exception 'ASSERT export idempotency';end if;
 select id into item from public.stock_take_items where stock_take_id=take and product_id=p;
 select quantity into before_qty from public.stock where product_id=p;
 rows:=jsonb_build_array(jsonb_build_object('item_id',item,'same',true,'quantity',99999));
 if public.import_stock_take_template(s,export_id,rows)<>take then raise exception 'ASSERT imported take';end if;
 if (select counted_qty from public.stock_take_items where id=item)<>before_qty then raise exception 'ASSERT TRUE uses server snapshot';end if;
 if (select quantity from public.stock where product_id=p)<>before_qty then raise exception 'ASSERT import never applies stock';end if;
 if public.import_stock_take_template(s,export_id,rows)<>take then raise exception 'ASSERT idempotent import';end if;
 begin perform public.import_stock_take_template(s,export_id,jsonb_build_array(jsonb_build_object('item_id',item,'same',false,'quantity',5)));raise exception 'ASSERT imported workbook immutable';exception when others then if sqlerrm<>'TEMPLATE_ALREADY_IMPORTED' then raise;end if;end;
 begin perform public.complete_stock_take(take);raise exception 'ASSERT employee cannot approve import';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 begin perform public.import_stock_take_template(other_store,export_id,rows);raise exception 'ASSERT cross store denied';exception when others then if sqlerrm<>'TEMPLATE_NOT_FOUND' then raise;end if;end;
 begin perform public.export_stock_take_template(other_store,gen_random_uuid(),take);raise exception 'ASSERT cross store export denied';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 -- Even stock that moves away and returns to the same balance invalidates the snapshot.
 export_id:=gen_random_uuid();template:=public.export_stock_take_template(s,export_id,take);
 perform public.complete_sale(s,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_cost',5)));
 begin perform public.import_stock_take_template(s,export_id,rows);raise exception 'ASSERT movement revision mismatch';exception when others then if sqlerrm<>'TEMPLATE_STOCK_CHANGED' then raise;end if;end;
 export_id:=gen_random_uuid();template:=public.export_stock_take_template(s,export_id,take);
 perform public.save_stock_take_count(item,12);
 begin perform public.import_stock_take_template(s,export_id,rows);raise exception 'ASSERT existing count preserved';exception when others then if sqlerrm<>'TEMPLATE_COUNT_CHANGED' then raise;end if;end;
 export_id:=gen_random_uuid();template:=public.export_stock_take_template(s,export_id,take);
 rows:=jsonb_build_array(jsonb_build_object('item_id',item,'same',false,'quantity',13),jsonb_build_object('item_id',gen_random_uuid(),'same',false,'quantity',1));
 begin perform public.import_stock_take_template(s,export_id,rows);raise exception 'ASSERT alien item rejected atomically';exception when others then if sqlerrm<>'TEMPLATE_ITEM_MISMATCH' then raise;end if;end;
 if (select counted_qty from public.stock_take_items where id=item)<>12 then raise exception 'ASSERT no partial import';end if;
 rows:=jsonb_build_array(jsonb_build_object('item_id',item,'same',false,'quantity',0));
 perform public.import_stock_take_template(s,export_id,rows);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 perform public.complete_stock_take(take);
 if (select quantity from public.stock where product_id=p)<>0 then raise exception 'ASSERT owner approves zero count';end if;
 if exists(select 1 from public.reconcile_stock(s) where diff<>0) then raise exception 'ASSERT stock reconciles';end if;
 -- Fresh permission checks precede even idempotent retries.
 v:=public.set_store_module_access(membership,s,'{"stock_take":false}',v);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 begin perform public.import_stock_take_template(s,export_id,rows);raise exception 'ASSERT revoked access denied';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 reset role;raise exception 'TESTS_PASSED';
end $$;
