do $$
declare u uuid:=gen_random_uuid(); worker uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); biz uuid; loc uuid; foreign_loc uuid; p uuid; c uuid;
  res jsonb; preview jsonb; rows jsonb; prepared jsonb; request uuid; before_count integer; prior_qty numeric;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(u,'imports-owner@test.invalid','{}'),(worker,'imports-worker@test.invalid','{}'),(other,'imports-other@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true); set local role authenticated;
  res:=public.create_business('Import tests','Shop'); biz:=(res->>'business_id')::uuid;loc:=(res->>'store_id')::uuid;
  rows:='[{"name":"Milk","barcode":"000123","cost_price":5,"selling_price":10,"quantity":6,"track_expiry":true,"expiry_date":"2027-01-01"}]';
  preview:=public.import_excel(loc,'products',rows,gen_random_uuid(),true);
  if not (preview->>'ok')::boolean then raise exception 'ASSERT preview %',preview; end if;
  if exists(select 1 from public.products where store_id=loc) or exists(select 1 from public.import_batches where store_id=loc) then raise exception 'ASSERT preview must roll back all writes'; end if;
  request:=gen_random_uuid();res:=public.import_excel(loc,'products',rows,request,false);
  if not (res->>'ok')::boolean then raise exception 'ASSERT create %',res; end if;p:=(res#>>'{rows,0,id}')::uuid;
  if public.import_excel(loc,'products',rows,request,false)<>res then raise exception 'ASSERT same import retry'; end if;
  if (select quantity from public.stock where product_id=p)<>6 or (select sum(quantity) from public.stock_batches where product_id=p)<>6 then raise exception 'ASSERT imported stock and expiry'; end if;
  rows:=jsonb_build_array(jsonb_build_object('barcode','000123','quantity',4)); preview:=public.import_excel(loc,'products',rows,gen_random_uuid(),true);
  prepared:=jsonb_build_array(preview#>'{rows,0,input}');
  perform public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
  res:=public.import_excel(loc,'products',prepared,gen_random_uuid(),false);
  if (res->>'ok')::boolean or res->>'error'<>'STOCK_CHANGED_REVIEW_AGAIN' then raise exception 'ASSERT stale quantity rejected %',res; end if;
  preview:=public.import_excel(loc,'products',rows,gen_random_uuid(),true); prepared:=jsonb_build_array(preview#>'{rows,0,input}');
  res:=public.import_excel(loc,'products',prepared,gen_random_uuid(),false);
  if not (res->>'ok')::boolean or (select sum(quantity) from public.stock_batches where product_id=p)<>4 then raise exception 'ASSERT FEFO decrease %',res; end if;
  if (select quantity from public.stock where product_id=p)<>(select sum(quantity_delta) from public.stock_movements where product_id=p) then raise exception 'ASSERT import ledger reconciliation'; end if;
  select count(*) into before_count from public.products where store_id=loc;
  res:=public.import_excel(loc,'products','[{"name":"Roll back"},{"name":"Invalid","quantity":-1}]',gen_random_uuid(),false);
  if (res->>'ok')::boolean or (select count(*) from public.products where store_id=loc)<>before_count then raise exception 'ASSERT atomic invalid row rollback'; end if;
  res:=public.import_excel(loc,'products','[{"name":"Same","barcode":"DUP"},{"barcode":"DUP"}]',gen_random_uuid(),true);
  if res->>'error'<>'DUPLICATE_RECORD_IN_FILE' then raise exception 'ASSERT duplicate record detection %',res; end if;
  res:=public.import_excel(loc,'suppliers','[{"name":"Wholesale","phone":"0123456789","email":"sup@example.test"}]',gen_random_uuid(),false);
  if not (res->>'ok')::boolean then raise exception 'ASSERT supplier import %',res; end if;
  res:=public.import_excel(loc,'customers','[{"name":"Customer","credit_limit":100}]',gen_random_uuid(),false);c:=(res#>>'{rows,0,id}')::uuid;
  if not (res->>'ok')::boolean or (select credit_limit from public.credit_accounts where customer_id=c)<>100 or (select balance from public.credit_accounts where customer_id=c)<>0 then raise exception 'ASSERT customer limit without invented debt %',res; end if;
  reset role;
  insert into public.memberships(business_id,user_id,role) values(biz,worker,'employee');insert into public.store_memberships(business_id,store_id,membership_id) select biz,loc,id from public.memberships where business_id=biz and user_id=worker;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',worker,'role','authenticated')::text,true);set local role authenticated;
  begin perform public.import_excel(loc,'products','[{"name":"Forbidden"}]',gen_random_uuid(),false);raise exception 'ASSERT employee import denied';exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if;end;
  if exists(select 1 from public.import_batches where store_id=loc) then raise exception 'ASSERT employee cannot read import payloads';end if;
  reset role;perform set_config('request.jwt.claims',jsonb_build_object('sub',other,'role','authenticated')::text,true);set local role authenticated;
  res:=public.create_business('Other import tests','Shop');foreign_loc:=(res->>'store_id')::uuid;
  res:=public.import_excel(foreign_loc,'products',jsonb_build_array(jsonb_build_object('id',p,'name','Stolen')),gen_random_uuid(),true);
  if (res->>'ok')::boolean or res->>'error'<>'PRODUCT_NOT_FOUND' then raise exception 'ASSERT cross-tenant product denied %',res;end if;
  reset role;raise exception 'TESTS_PASSED';
end $$;
