do $$
declare u uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); otherowner uuid:=gen_random_uuid(); biz uuid; loc uuid; member uuid;
  res jsonb; c uuid; p uuid; oid uuid; iid uuid; iid2 uuid; entry uuid; req uuid:=gen_random_uuid(); payload jsonb; b public.v_invoice_balances%rowtype; blocked boolean; q numeric;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(u,'invoice-owner@test.invalid','{}'),(employee,'invoice-employee@test.invalid','{}'),(otherowner,'invoice-other@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true); set local role authenticated;
  res:=public.create_business('Invoice test','Shop'); biz:=(res->>'business_id')::uuid; loc:=(res->>'store_id')::uuid;
  member:=public.add_member_by_email(biz,'invoice-employee@test.invalid','employee'); perform public.set_member_locations(member,array[loc]);
  insert into public.customers(business_id,store_id,name) values(biz,loc,'Invoice customer') returning id into c;
  p:=public.create_product(loc,'Product','INVOICE-PRODUCT',null,null,5,10);
  perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',20)));
  perform public.set_billing_settings(biz,15,true);
  payload:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10));
  oid:=public.create_sales_order(loc,c,payload,req);
  if oid<>public.create_sales_order(loc,c,payload,req) then raise exception 'ASSERT order retry'; end if;
  blocked:=false; begin perform public.create_sales_invoice(oid,current_date+30,'CASH',10); exception when others then if sqlerrm<>'ORDER_NOT_CONFIRMED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT confirm before invoice'; end if;
  perform public.process_sales_order(oid,'confirm');
  iid:=public.create_sales_invoice(oid,current_date+30,'CASH',10);
  if iid<>public.create_sales_invoice(oid,current_date+30,'CASH',10) then raise exception 'ASSERT invoice retry'; end if;
  if (select total from public.sales_invoices where id=iid)<>103.50 then raise exception 'ASSERT tax after discount'; end if;
  if (select sum(net_total) from public.sales_invoice_items where invoice_id=iid)<>103.50 then raise exception 'ASSERT line total allocation'; end if;
  perform public.issue_sales_invoice(iid); perform public.issue_sales_invoice(iid);
  if (select balance from public.credit_accounts where customer_id=c)<>103.50 then raise exception 'ASSERT invoice receivable once'; end if;
  if (select quantity from public.stock where product_id=p)<>20 then raise exception 'ASSERT invoicing does not issue stock'; end if;
  blocked:=false; begin perform public.issue_invoice_goods(iid); exception when others then if sqlerrm<>'INVOICE_PAYMENT_REQUIRED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT unpaid cash goods denied'; end if;
  req:=gen_random_uuid(); entry:=public.post_invoice_entry(iid,'PAYMENT',50,req,'CARD_EFT','SLIP-1');
  if entry<>public.post_invoice_entry(iid,'PAYMENT',50,req,'CARD_EFT','SLIP-1') then raise exception 'ASSERT payment retry'; end if;
  select * into b from public.v_invoice_balances where id=iid;
  if b.outstanding<>53.50 or b.status<>'PARTIALLY_PAID' then raise exception 'ASSERT partial payment status'; end if;
  blocked:=false; begin perform public.post_invoice_entry(iid,'PAYMENT',54,gen_random_uuid(),'CASH'); exception when others then if sqlerrm<>'PAYMENT_EXCEEDS_OUTSTANDING' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT overpayment denied'; end if;
  blocked:=false; begin perform public.record_credit_payment(c,1); exception when others then if sqlerrm<>'SELECT_INVOICE_FOR_PAYMENT' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT invoice allocation required'; end if;
  perform public.post_invoice_entry(iid,'PAYMENT',53.50,gen_random_uuid(),'CASH');
  if not exists(select 1 from public.v_invoice_payment_report where id=iid and payment_methods @> array['CASH','CARD_EFT']::text[] and terms='CASH') then raise exception 'ASSERT mixed receipt method filtering'; end if;
  perform public.issue_invoice_goods(iid); perform public.issue_invoice_goods(iid);
  if (select quantity from public.stock where product_id=p)<>10 then raise exception 'ASSERT stock issues once'; end if;
  if (select balance from public.credit_accounts where customer_id=c)<>0 then raise exception 'ASSERT paid invoice clears customer balance'; end if;
  perform public.post_invoice_entry(iid,'DEBIT_NOTE',5,gen_random_uuid(),null,null,'Delivery correction');
  perform public.post_invoice_entry(iid,'CREDIT_NOTE',2,gen_random_uuid(),null,null,'Courtesy adjustment');
  if (select outstanding from public.v_invoice_balances where id=iid)<>3 then raise exception 'ASSERT debit and credit reconciliation'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
  blocked:=false; begin perform public.post_invoice_entry(iid,'CREDIT_NOTE',1,gen_random_uuid(),null,null,'Forbidden'); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT notes require manager'; end if;
  blocked:=false; begin update public.sales_invoices set total=1 where id=iid; exception when insufficient_privilege then blocked:=true; end;
  if not blocked then raise exception 'ASSERT API cannot edit invoice'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  oid:=public.create_sales_order(loc,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),gen_random_uuid());
  perform public.process_sales_order(oid,'confirm'); iid2:=public.create_sales_invoice(oid,current_date-1,'CREDIT'); perform public.issue_sales_invoice(iid2);
  if (select status from public.v_invoice_balances where id=iid2)<>'OVERDUE' then raise exception 'ASSERT overdue'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
  blocked:=false; begin perform public.issue_invoice_goods(iid2,true); exception when others then if sqlerrm<>'OVERRIDE_NOT_AUTHORIZED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT credit release limit'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  perform public.cancel_sales_invoice(iid2,'Customer cancelled');
  if (select balance from public.credit_accounts where customer_id=c)<>3 then raise exception 'ASSERT void reverses debt'; end if;
  if (select status from public.v_invoice_balances where id=iid2)<>'VOID' then raise exception 'ASSERT void retained'; end if;
  if exists(select 1 from public.reconcile_stock(loc) where diff<>0) then raise exception 'ASSERT invoice stock reconciles'; end if;
  select sum(amount) into q from public.credit_transactions where business_id=biz;
  if q<>3 then raise exception 'ASSERT customer ledger reconciles'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',otherowner,'role','authenticated')::text,true);
  if exists(select 1 from public.v_invoice_payment_report) then raise exception 'ASSERT payment report tenant isolation'; end if;
  if exists(select 1 from public.sales_invoices) or exists(select 1 from public.invoice_entries) or exists(select 1 from public.sales_order_items) then raise exception 'ASSERT foreign invoice RLS'; end if;
  blocked:=false; begin perform public.issue_sales_invoice(iid); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT foreign RPC denied'; end if;
  reset role; raise exception 'TESTS_PASSED';
end $$;
