do $$
declare u uuid:=gen_random_uuid(); b uuid; s uuid; c uuid; guest uuid; p uuid; q uuid; o uuid; i uuid; line uuid; r uuid; r2 uuid; sale uuid; req uuid:=gen_random_uuid(); items jsonb; result jsonb; blocked boolean; before_balance numeric; before_entries integer;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'invoice-refinements@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 result:=public.create_business('Invoice refinements','Shop');b:=(result->>'business_id')::uuid;s:=(result->>'store_id')::uuid;
 insert into public.customers(business_id,store_id,name) values(b,s,'Registered account') returning id into c;
 p:=public.create_product(s,'Refinement item','REFINE-1',null,null,5,10,0,0,'each',false);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',30)));
 items:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2));
 q:=public.save_quote(s,null,items,current_date+30,0,'Guest',req,null,0,'{"name":"One-off buyer","phone":"0123456789","address":"12 Main Street"}');
 if q<>public.save_quote(s,null,items,current_date+30,0,'Guest',req,null,0,'{"name":"One-off buyer","phone":"0123456789","address":"12 Main Street"}') then raise exception 'ASSERT guest retry';end if;
 select customer_id into guest from public.sales_quotes where id=q;
 if not exists(select 1 from public.customers where id=guest and is_once_off and address='12 Main Street') then raise exception 'ASSERT guest contact';end if;
 if exists(select 1 from public.v_credit_customers where customer_id=guest) then raise exception 'ASSERT guest excluded from registered accounts';end if;
 perform public.save_quote(s,null,items,current_date+30,0,'Guest edited',gen_random_uuid(),q,1,'{"name":"One-off revised"}');
 if (select customer_id from public.sales_quotes where id=q)<>guest or (select name from public.customers where id=guest)<>'One-off revised' then raise exception 'ASSERT guest edit keeps contact';end if;
 perform public.save_purchase_order(q,null,true,true,'PO-BEFORE',null,null,null,0);
 perform public.set_quote_status(q,'ACCEPTED',2);
 blocked:=false;begin perform public.save_purchase_order(q,null,false,false,'PO-AFTER',null,null,null,1);exception when others then if sqlerrm<>'PURCHASE_ORDER_LOCKED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT accepted PO lock';end if;
 if (select reference from public.sales_purchase_orders where quote_id=q)<>'PO-BEFORE' then raise exception 'ASSERT PO preserved';end if;
 o:=public.convert_quote(q,items,3);perform public.process_sales_order(o,'confirm');
 blocked:=false;begin perform public.create_sales_invoice(o,current_date+30,'CREDIT');exception when others then if sqlerrm<>'REGISTERED_CREDIT_CUSTOMER_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT guest credit denied';end if;
 i:=public.create_sales_invoice(o,current_date+30,'CASH');perform public.issue_sales_invoice(i);
 blocked:=false;begin perform public.use_invoice_customer_credit(i,guest);exception when others then if sqlerrm<>'REGISTERED_INVOICE_CUSTOMER_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT guest switch denied';end if;
 perform public.post_invoice_entry(i,'PAYMENT',20,gen_random_uuid(),'CASH');perform public.issue_invoice_goods(i);
 select id into line from public.sales_invoice_items where invoice_id=i;
 if jsonb_array_length(public.returnable_documents(s,'invoice'))<>1 then raise exception 'ASSERT invoice initially returnable';end if;
 r:=public.submit_goods_return('invoice',i,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 if (select remaining_quantity from public.v_returnable_items where item_id=line)<>1 then raise exception 'ASSERT pending return reserves quantity';end if;
 if (public.returnable_documents(s,'invoice')->0->'items'->0->>'remaining')::numeric<>1 then raise exception 'ASSERT partial invoice remains';end if;
 r2:=public.submit_goods_return('invoice',i,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 if jsonb_array_length(public.returnable_documents(s,'invoice'))<>0 then raise exception 'ASSERT fully reserved invoice hidden';end if;
 blocked:=false;begin perform public.submit_goods_return('invoice',i,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());exception when others then if sqlerrm<>'RETURN_EXCEEDS_SOLD_QUANTITY' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT repeat return blocked';end if;
 perform public.process_goods_return(r2,false,'Rejected after inspection');
 if jsonb_array_length(public.returnable_documents(s,'invoice'))<>1 then raise exception 'ASSERT rejection restores source';end if;
 perform public.process_goods_return(r,true);
 if (select remaining_quantity from public.v_returnable_items where item_id=line)<>1 then raise exception 'ASSERT approval does not double reserve';end if;
 sale:=public.complete_sale(s,'CASH',null,items);
 select id into line from public.goods_out_items where goods_out_id=sale;
 r:=public.submit_goods_return('sale',sale,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',2,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 if exists(select 1 from jsonb_array_elements(public.returnable_documents(s,'sale')) x where x->>'id'=sale::text) then raise exception 'ASSERT fully returned checkout hidden';end if;
 o:=public.create_sales_order(s,c,items,gen_random_uuid());perform public.process_sales_order(o,'confirm');i:=public.create_sales_invoice(o,current_date+30,'CASH');perform public.issue_sales_invoice(i);
 select balance into before_balance from public.credit_accounts where customer_id=c;select count(*) into before_entries from public.invoice_entries where invoice_id=i;
 perform public.use_invoice_customer_credit(i,c);perform public.use_invoice_customer_credit(i,c);
 if (select terms from public.sales_invoices where id=i)<>'CREDIT' or (select balance from public.credit_accounts where customer_id=c)<>before_balance or (select count(*) from public.invoice_entries where invoice_id=i)<>before_entries then raise exception 'ASSERT credit switch adds no receipt or duplicate debt';end if;
 blocked:=false;begin perform public.use_invoice_customer_credit(i,guest);exception when others then if sqlerrm<>'REGISTERED_INVOICE_CUSTOMER_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT cannot reassign invoice customer';end if;
 blocked:=false;begin perform public.issue_invoice_goods(i);exception when others then if sqlerrm<>'OVERRIDE_NOT_AUTHORIZED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT credit limit still enforced';end if;
 perform public.issue_invoice_goods(i,true);
 if not exists(select 1 from public.sales_invoices where id=i and goods_issued_by=u and authorized_by=u) then raise exception 'ASSERT actual salesperson and override approver retained';end if;
 sale:=public.complete_sale(s,'CREDIT',c,items,true);
 if not exists(select 1 from public.goods_out where id=sale and performed_by=u and authorized_by=u and credit_override) then raise exception 'ASSERT checkout report staff';end if;
 blocked:=false;begin perform public.returnable_documents(gen_random_uuid(),'sale');exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT source store authorization';end if;
 raise exception 'TESTS_PASSED';
end $$;

