do $$
declare u uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); r jsonb; biz uuid; shop uuid; wh uuid; individual_id uuid; wu uuid; pack uuid; wp uuid; wrong uuid; c uuid; wc uuid; t uuid; req uuid:=gen_random_uuid(); before_count int; blocked boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'bulk-create-owner@test.invalid','{}'),(employee,'bulk-create-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 r:=public.create_business('Location bulk receiving','Shop');biz:=(r->>'business_id')::uuid;shop:=(r->>'store_id')::uuid;wh:=public.create_location(biz,'Warehouse','warehouse');
 individual_id:=public.create_product(shop,'Banana juice','UNIT-BANANA',null,null,2,3);
 perform public.sync_warehouse_products(wh,shop,false);select id into wu from public.products where store_id=wh and name='Banana juice';
 pack:=public.create_bulk_product(shop,individual_id,'Banana juice case',6,'BANANA-CASE','CASE-BANANA',12,18,req);
 if public.create_bulk_product(shop,individual_id,'Banana juice case',6,'BANANA-CASE','CASE-BANANA',12,18,req)<>pack then raise exception 'ASSERT retry returns same product';end if;
 begin perform public.create_bulk_product(shop,individual_id,'Banana juice case',7,'BANANA-CASE','CASE-BANANA',12,18,req);raise exception 'ASSERT changed retry';exception when others then if sqlerrm<>'REQUEST_CONFLICT' then raise;end if;end;
 begin perform public.create_bulk_product(wh,individual_id,'Wrong location',6,'WRONG','',12,18,gen_random_uuid());raise exception 'ASSERT cross-location individual';exception when others then if sqlerrm<>'INDIVIDUAL_PRODUCT_REQUIRED' then raise;end if;end;
 wp:=public.create_bulk_product(wh,wu,'Banana juice case',6,'BANANA-CASE','CASE-BANANA',12,18,gen_random_uuid());
 if (select item_type from public.v_product_catalog where id=pack)<>'Bulk Stock' or (select item_type from public.v_product_catalog where id=individual_id)<>'Individual' then raise exception 'ASSERT product types';end if;
 if exists(select 1 from public.stock where product_id in(pack,wp,individual_id,wu) and quantity<>0) then raise exception 'ASSERT setup has no stock';end if;
 select id into c from public.bulk_conversions where pack_product_id=pack;select id into wc from public.bulk_conversions where pack_product_id=wp;
 perform public.receive_stock(shop,null,null,null,jsonb_build_array(jsonb_build_object('product_id',pack,'quantity',5)));
 perform public.receive_stock(wh,null,null,null,jsonb_build_array(jsonb_build_object('product_id',wp,'quantity',10)));
 select count(*) into before_count from public.products where business_id=biz;
 perform public.unpack_stock(wc,2,'Warehouse shelf',gen_random_uuid());
 if (select quantity from public.stock where product_id=pack)<>5 or (select quantity from public.stock where product_id=individual_id)<>0 then raise exception 'ASSERT warehouse leaves store untouched';end if;
 perform public.unpack_stock(c,2,'Store shelf',gen_random_uuid());
 if (select quantity from public.stock where product_id=wp)<>8 or (select quantity from public.stock where product_id=wu)<>12 then raise exception 'ASSERT store leaves warehouse untouched';end if;
 begin perform public.unpack_stock(c,4,'Too many',gen_random_uuid());raise exception 'ASSERT insufficient packs';exception when others then if sqlerrm not like 'INSUFFICIENT_STOCK%' then raise;end if;end;
 begin perform public.receive_stock(shop,null,null,null,jsonb_build_array(jsonb_build_object('product_id',pack,'quantity',0.5)));raise exception 'ASSERT fractional pack';exception when others then if sqlerrm<>'WHOLE_PACKS_REQUIRED' then raise;end if;end;
 wrong:=public.create_product(shop,'Unlinked case',null,null,null,12,18,0,0,'pack');
 begin perform public.create_stock_transfer(wh,shop,jsonb_build_array(jsonb_build_object('source_product_id',wp,'destination_product_id',wrong,'quantity',1)),gen_random_uuid());raise exception 'ASSERT bulk to individual blocked';exception when others then if sqlerrm<>'BULK_TRANSFER_MISMATCH' then raise;end if;end;
 perform public.set_bulk_conversion(pack,individual_id,12);
 begin perform public.save_warehouse_transfer(wh,shop,jsonb_build_array(jsonb_build_object('source_product_id',wp,'quantity',1)),gen_random_uuid());raise exception 'ASSERT ratio mismatch';exception when others then if sqlerrm<>'BULK_TRANSFER_MISMATCH' then raise;end if;end;
 perform public.set_bulk_conversion(pack,individual_id,6);
 t:=public.save_warehouse_transfer(wh,shop,jsonb_build_array(jsonb_build_object('source_product_id',wp,'quantity',3)),gen_random_uuid());
 begin perform public.set_bulk_conversion(pack,individual_id,7);raise exception 'ASSERT pending conversion blocked';exception when others then if sqlerrm<>'BULK_TRANSFER_PENDING' then raise;end if;end;
 perform public.submit_warehouse_transfer(t);
 if (select quantity from public.stock where product_id=wp)<>5 or (select quantity from public.stock where product_id=pack)<>3 then raise exception 'ASSERT dispatch in transit';end if;
 perform public.receive_warehouse_transfer(t,shop);perform public.receive_warehouse_transfer(t,shop);
 if (select quantity from public.stock where product_id=pack)<>6 or (select quantity from public.stock where product_id=individual_id)<>12 then raise exception 'ASSERT receipt stays bulk';end if;
 perform public.unpack_stock(c,1,'Delivered pack',gen_random_uuid());
 if (select quantity from public.stock where product_id=pack)<>5 or (select quantity from public.stock where product_id=individual_id)<>18 or (select quantity from public.stock where product_id=wp)<>5 or (select quantity from public.stock where product_id=wu)<>12 then raise exception 'ASSERT final location balances';end if;
 if (select count(*) from public.products where business_id=biz)<>before_count+1 then raise exception 'ASSERT unpack creates no products';end if;
 if (select count(*) from public.bulk_unpackings where store_id=shop)<>2 or (select count(*) from public.bulk_unpackings where store_id=wh)<>1 then raise exception 'ASSERT local history';end if;
 reset role;insert into public.memberships(business_id,user_id,role) values(biz,employee,'employee');insert into public.store_memberships(business_id,store_id,membership_id) select biz,shop,id from public.memberships where business_id=biz and user_id=employee;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);set local role authenticated;
 begin perform public.create_bulk_product(shop,individual_id,'Unauthorized',6,'UNAUTH','',12,18,gen_random_uuid());raise exception 'ASSERT employee cannot configure';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 reset role;if has_function_privilege('anon','public.create_bulk_product(uuid,uuid,text,integer,text,text,numeric,numeric,uuid)','execute') then raise exception 'ASSERT anonymous denied';end if;
 raise exception 'TESTS_PASSED';
end $$;
