-- Run after 0013. Exercises actual authenticated RLS and SECURITY DEFINER RPCs.
do $$
declare
  owner_id uuid := gen_random_uuid(); manager_id uuid := gen_random_uuid(); employee_id uuid := gen_random_uuid();
  biz uuid; shop uuid; other_shop uuid; warehouse uuid; foreign_biz uuid; foreign_shop uuid;
  manager_member uuid; employee_member uuid; warehouse_product uuid; shop_product uuid;
  res jsonb; n int; q numeric; blocked boolean; st uuid;
begin
  insert into auth.users(id,email,raw_user_meta_data) values
    (owner_id, 'location-owner@test.invalid', '{}'), (manager_id, 'location-manager@test.invalid', '{}'),
    (employee_id, 'location-employee@test.invalid', '{}');
  perform set_config('request.jwt.claims', jsonb_build_object('sub',owner_id,'role','authenticated')::text, true);
  set local role authenticated;
  res := public.create_business('Locations test', 'Main shop');
  biz := (res->>'business_id')::uuid; shop := (res->>'store_id')::uuid;
  warehouse := public.create_location(biz, 'Warehouse', 'warehouse');
  other_shop := public.create_location(biz, 'Second shop', 'store');
  res := public.create_business('Other business', 'Foreign shop');
  foreign_biz := (res->>'business_id')::uuid; foreign_shop := (res->>'store_id')::uuid;
  manager_member := public.add_member_by_email(biz,'location-manager@test.invalid','manager');
  employee_member := public.add_member_by_email(biz,'location-employee@test.invalid','employee');
  perform public.set_member_locations(manager_member, array[shop,warehouse]);
  perform public.set_member_locations(employee_member, array[shop]);
  warehouse_product := public.create_product(warehouse, 'Milk warehouse', 'WH-MILK');
  shop_product := public.create_product(shop, 'Milk shop', 'SHOP-MILK');
  perform public.receive_stock(warehouse,null,'WH-RECEIPT',null,jsonb_build_array(jsonb_build_object('product_id',warehouse_product,'quantity',10)));
  select quantity into q from public.stock where product_id=warehouse_product and store_id=warehouse;
  if q is distinct from 10 then raise exception 'ASSERT warehouse receipt'; end if;
  select quantity into q from public.stock where product_id=shop_product and store_id=shop;
  if q is distinct from 0 then raise exception 'ASSERT warehouse receipt must not increase shop stock'; end if;
  select stock_quantity into q from public.business_location_summary(biz) where location_id=warehouse;
  if q is distinct from 10 then raise exception 'ASSERT global overview warehouse stock'; end if;
  select count(*) into n from public.business_location_summary(biz);
  if n <> 3 then raise exception 'ASSERT global overview business isolation'; end if;
  st := public.start_stock_take(shop);
  if exists(select 1 from public.stock_take_items where stock_take_id=st and product_id=warehouse_product) then raise exception 'ASSERT warehouse excluded from shop stock take'; end if;
  st := public.start_stock_take(warehouse);
  if not exists(select 1 from public.stock_take_items where stock_take_id=st and product_id=warehouse_product and system_qty=10) then raise exception 'ASSERT dedicated warehouse stock take'; end if;
  blocked := false;
  begin perform public.complete_sale(warehouse,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',warehouse_product,'quantity',1)));
  exception when others then if sqlerrm <> 'LOCATION_NOT_SALEABLE' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT warehouse sale denied'; end if;
  if exists(select 1 from public.reconcile_stock(warehouse) where diff <> 0) then raise exception 'ASSERT warehouse reconciles'; end if;
  blocked := false;
  begin perform public.set_member_locations(employee_member, array[foreign_shop]);
  exception when others then if sqlerrm <> 'INVALID_LOCATION' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT cross-business assignment denied'; end if;
  if not exists(select 1 from public.store_memberships where membership_id=employee_member and store_id=shop) then raise exception 'ASSERT invalid assignment rollback'; end if;

  perform set_config('request.jwt.claims', jsonb_build_object('sub',manager_id,'role','authenticated')::text, true);
  select count(*) into n from public.stores;
  if n <> 2 then raise exception 'ASSERT manager sees only 2 assigned locations, got %', n; end if;
  if app.has_store_role(other_shop,'manager') then raise exception 'ASSERT manager rank cannot bypass assignment'; end if;
  blocked := false;
  begin perform public.business_location_summary(biz);
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT manager cannot use global overview'; end if;
  perform public.update_location(shop,'Renamed shop');
  blocked := false;
  begin perform public.update_location(other_shop,'Forbidden rename');
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT unassigned rename denied'; end if;
  blocked := false;
  begin perform public.create_location(biz,'Forbidden shop','store');
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT manager cannot create location'; end if;
  blocked := false;
  begin perform public.adjust_stock(other_shop,shop_product,5,'OTHER');
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT unassigned adjustment denied'; end if;
  if exists(select 1 from public.audit_logs where store_id=other_shop or store_id is null) then raise exception 'ASSERT manager audit isolation'; end if;

  perform set_config('request.jwt.claims', jsonb_build_object('sub',employee_id,'role','authenticated')::text, true);
  if exists(select 1 from public.stock where store_id=warehouse) then raise exception 'ASSERT warehouse stock hidden'; end if;
  perform public.receive_stock(shop,null,null,null,jsonb_build_array(jsonb_build_object('product_id',shop_product,'quantity',3)));
  perform public.complete_sale(shop,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',shop_product,'quantity',1)));
  select quantity into q from public.stock where product_id=shop_product and store_id=shop;
  if q is distinct from 2 then raise exception 'ASSERT employee can operate assigned shop'; end if;
  blocked := false;
  begin perform public.receive_stock(warehouse,null,null,null,jsonb_build_array(jsonb_build_object('product_id',warehouse_product,'quantity',1)));
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT employee warehouse receipt denied'; end if;
  blocked := false;
  begin perform public.set_member_locations(employee_member,array[shop,warehouse]);
  exception when others then if sqlerrm <> 'FORBIDDEN' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT no self-assignment'; end if;
  blocked := false;
  begin insert into public.store_memberships(membership_id,store_id,business_id) values(employee_member,warehouse,biz);
  exception when insufficient_privilege then blocked := true; end;
  if not blocked then raise exception 'ASSERT direct assignment denied'; end if;
  blocked := false;
  begin perform app.apply_stock_delta(biz,shop,shop_product,100,'GOODS_IN','forged',null,null);
  exception when insufficient_privilege then blocked := true; end;
  if not blocked then raise exception 'ASSERT internal ledger helper denied'; end if;
  blocked := false;
  begin insert into public.products(business_id,store_id,name) values(foreign_biz,shop,'Forged business');
  exception when others then if sqlerrm <> 'INVALID_LOCATION' then raise; end if; blocked := true; end;
  if not blocked then raise exception 'ASSERT product business validated'; end if;

  perform set_config('request.jwt.claims', jsonb_build_object('sub',owner_id,'role','authenticated')::text, true);
  perform public.set_member_locations(employee_member,array[]::uuid[]);
  perform set_config('request.jwt.claims', jsonb_build_object('sub',employee_id,'role','authenticated')::text, true);
  if exists(select 1 from public.stores) or app.has_store_access(shop) then raise exception 'ASSERT revoked access immediate'; end if;
  set local role anon;
  blocked := false;
  begin perform public.create_location(biz,'Anonymous','store');
  exception when insufficient_privilege then blocked := true; end;
  if not blocked then raise exception 'ASSERT anonymous RPC denied'; end if;
  reset role;
  raise exception 'TESTS_PASSED';
end $$;
