-- Existing workflow fixture grants are explicit; see explicit_access_fixtures.sql.
do $$
#variable_conflict use_variable
declare u uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 b uuid; s uuid; s2 uuid; wh uuid; b2 uuid; t2 uuid; p uuid; wp uuid; c uuid; q uuid; member uuid; sale uuid; transfer uuid;
 req uuid:=gen_random_uuid(); treq uuid:=gen_random_uuid(); result jsonb; items jsonb; lines jsonb; n bigint; approval_time timestamptz;
 day date:=(statement_timestamp() at time zone 'Africa/Johannesburg')::date; prefix text;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'mixed-owner@test.invalid','{}'),(staff,'mixed-staff@test.invalid','{}'),(outsider,'mixed-outsider@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 result:=public.create_business('Mixed changes','Shop');b:=(result->>'business_id')::uuid;s:=(result->>'store_id')::uuid;
 s2:=public.create_location(b,'Second shop','store');wh:=public.create_location(b,'Warehouse','warehouse');
 p:=public.create_product(s,'Item',null,null,null,1,10);wp:=public.create_product(wh,'Item',null,null,null,1,10);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',20)));
 insert into public.customers(business_id,store_id,name) values(b,s,'Customer') returning id into c;
 items:=jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10));
 q:=public.save_quote(s,c,items,current_date+30,0,null,gen_random_uuid());
 perform public.save_purchase_order(q,null,false,true,'PO-1',null,null,null,0);
 if not exists(select 1 from public.sales_purchase_orders where quote_id=q and approved and not received and approved_by=u) then raise exception 'ASSERT approval without receipt';end if;
 select approved_at into approval_time from public.sales_purchase_orders where quote_id=q;
 reset role;member:=app_test.add_member_by_email(b,'mixed-staff@test.invalid','employee');set local role authenticated;perform app_test.set_member_locations(member,array[s]);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 perform public.save_purchase_order(q,null,true,true,'PO-1',null,null,null,1);
 perform public.save_purchase_order(q,null,false,true,'PO-1',null,null,null,2);
 if not exists(select 1 from public.sales_purchase_orders where quote_id=q and approved and not received and approved_by=u and approved_at=approval_time and updated_by=staff) then raise exception 'ASSERT independent receipt preserves approver';end if;
 begin perform public.save_purchase_order(q,null,false,false,'PO-1',null,null,null,3);raise exception 'ASSERT employee revoked approval';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 begin perform public.save_purchase_order(q,null,false,true,'CHANGED',null,null,null,3);raise exception 'ASSERT employee changed approved content';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 begin perform public.save_purchase_order(q,null,true,true,'PO-1',null,null,null,2);raise exception 'ASSERT stale save';exception when others then if sqlerrm<>'PO_CHANGED_REFRESH' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated')::text,true);
 begin perform public.save_purchase_order(q,null,true,true,'PO-1',null,null,null,3);raise exception 'ASSERT cross tenant PO';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 perform public.save_purchase_order(q,null,true,false,'PO-1',null,null,null,3);
 if not exists(select 1 from public.sales_purchase_orders where quote_id=q and received and not approved and approved_by is null and approved_at is null) then raise exception 'ASSERT manager revokes independently';end if;
 perform public.save_purchase_order(q,null,false,false,'PO-1',null,null,null,4);
 begin perform public.save_purchase_order(q,null,null,false,'PO-1',null,null,null,5);raise exception 'ASSERT null state';exception when others then if sqlerrm<>'INVALID_PO_STATE' then raise;end if;end;
 sale:=public.complete_checkout(s,items,'[{"method":"CASH","amount":10}]',req);
 prefix:='POS-'||to_char(day,'YYYYMMDD')||'-';
 if not exists(select 1 from public.sale_receipts where sale_id=sale and reference=prefix||'001' and snapshot->>'reference'=reference) then raise exception 'ASSERT POS reference and snapshot';end if;
 if public.complete_checkout(s,items,'[{"method":"CASH","amount":10}]',req)<>sale then raise exception 'ASSERT checkout retry';end if;
 reset role;select value into n from app_private.document_sequences where business_id=b and kind='POS' and document_sequences.day=day;
 if n<>1 then raise exception 'ASSERT replay consumed number';end if;
 -- A previous day's counter must not affect today's sequence. Values over 999 expand.
 insert into app_private.document_sequences values(b,'POS',day-1,9999);
 update app_private.document_sequences set value=999 where business_id=b and kind='POS' and document_sequences.day=day;
 set local role authenticated;
 sale:=public.complete_checkout(s,items,'[{"method":"CASH","amount":10}]',gen_random_uuid());
 if (select reference from public.sale_receipts where sale_id=sale)<>prefix||'1000' then raise exception 'ASSERT no truncation after 999';end if;
 p:=public.create_product(s2,'Other store item',null,null,null,1,10);
 perform public.receive_stock(s2,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)));
 sale:=public.complete_checkout(s2,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10)),'[{"method":"CASH","amount":10}]',gen_random_uuid());
 if (select reference from public.sale_receipts where sale_id=sale)<>prefix||'1001' then raise exception 'ASSERT business wide POS sequence';end if;
 lines:=jsonb_build_array(jsonb_build_object('source_product_id',wp,'destination_product_id',p,'quantity',1));
 transfer:=public.create_stock_transfer(wh,s2,lines,treq);
 if (select reference from public.stock_transfers where id=transfer)<>'TR-'||to_char(day,'YYYYMMDD')||'-001' then raise exception 'ASSERT TR number';end if;
 if public.create_stock_transfer(wh,s2,lines,treq)<>transfer then raise exception 'ASSERT transfer replay';end if;
 reset role;
 begin update public.stock_transfers set reference='CHANGED' where id=transfer;raise exception 'ASSERT transfer reference mutable';exception when others then if sqlerrm<>'DOCUMENT_REFERENCE_LOCKED' then raise;end if;end;
 if (select value from app_private.document_sequences where business_id=b and kind='TR' and document_sequences.day=day)<>1 then raise exception 'ASSERT TR replay counter';end if;
 set local role authenticated;
 result:=public.create_business('Second business','Shop');b2:=(result->>'business_id')::uuid;t2:=(result->>'store_id')::uuid;
 p:=public.create_product(t2,'Second business item',null,null,null,1,10);perform public.receive_stock(t2,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)));
 sale:=public.complete_checkout(t2,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',10)),'[{"method":"CASH","amount":10}]',gen_random_uuid());
 if (select reference from public.sale_receipts where sale_id=sale)<>prefix||'001' then raise exception 'ASSERT isolated business sequence';end if;
 wh:=public.create_location(b2,'Warehouse','warehouse');wp:=public.create_product(wh,'Transfer item',null,null,null,1,10);
 transfer:=public.create_stock_transfer(wh,t2,jsonb_build_array(jsonb_build_object('source_product_id',wp,'destination_product_id',p,'quantity',1)),gen_random_uuid());
 if (select reference from public.stock_transfers where id=transfer)<>'TR-'||to_char(day,'YYYYMMDD')||'-001' then raise exception 'ASSERT TR isolated business';end if;
 if has_function_privilege('anon','public.save_purchase_order(uuid,uuid,boolean,boolean,text,text,text,text,bigint)','execute') then raise exception 'ASSERT anonymous access';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
