do $$
declare owner_id uuid:=gen_random_uuid(); employee_id uuid:=gen_random_uuid(); biz uuid; a uuid; b uuid; m uuid; p uuid; r jsonb; denied jsonb; blocked boolean; v bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(owner_id,'modules-owner@test.invalid','{}'),(employee_id,'modules-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true); set local role authenticated;
 r:=public.create_business('Module test','Store A'); biz:=(r->>'business_id')::uuid; a:=(r->>'store_id')::uuid;
 b:=public.create_location(biz,'Store B','store');
 m:=public.add_member_by_email(biz,'modules-staff@test.invalid','employee'); perform public.set_member_locations(m,array[a,b]);
 p:=public.create_product(a,'Test product','PERM-1');
 select jsonb_object_agg(key,false) into denied from public.module_catalog;
 v:=public.set_store_module_access(m,a,denied||'{"check_price":true}',0);
 if v<>1 then raise exception 'ASSERT first access version'; end if;
 blocked:=false; begin perform public.set_store_module_access(m,a,denied,0); exception when others then if sqlerrm<>'ACCESS_CHANGED_REFRESH' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT stale editor cannot overwrite'; end if;
 blocked:=false; begin perform public.set_store_module_access(m,a,'{"adjust":true}',1); exception when others then if sqlerrm<>'INVALID_PERMISSIONS' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT role cap'; end if;
 blocked:=false; begin perform public.set_store_module_access(m,a,'{"check_price":"yes"}',1); exception when others then if sqlerrm<>'INVALID_PERMISSIONS' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT strict booleans'; end if;
 if not app.has_module(a,'access_control') then raise exception 'ASSERT owner recovery'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee_id,'role','authenticated','user_metadata',jsonb_build_object('role','owner'))::text,true);
 if not app.has_module(a,'check_price') or app.has_module(a,'goods_out') or app.has_module(a,'settings') then raise exception 'ASSERT per-module defaults overridden'; end if;
 if not app.has_module(b,'goods_out') then raise exception 'ASSERT store B unaffected'; end if;
 if not exists(select 1 from public.products where id=p) then raise exception 'ASSERT price lookup remains available'; end if;
 blocked:=false; begin perform public.complete_sale(a,'CASH',null,'[]'); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT hidden checkout RPC denied'; end if;
 blocked:=false; begin perform public.create_product(a,'Forbidden'); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT lookup does not grant product creation'; end if;
 blocked:=false; begin insert into public.products(business_id,store_id,name) values(biz,a,'Direct forbidden'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'ASSERT direct insert denied'; end if;
 blocked:=false; begin perform app_private.complete_sale(a,'CASH',null,'[]'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'ASSERT private implementation denied'; end if;
 blocked:=false; begin perform public.set_store_module_access(m,a,'{}',1); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
 if not blocked then raise exception 'ASSERT no self grant'; end if;
 perform public.create_product(b,'Allowed at B');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 perform public.set_store_module_access(m,a,denied,1);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee_id,'role','authenticated')::text,true);
 if exists(select 1 from public.products where store_id=a) then raise exception 'ASSERT all-denied hides shared records'; end if;
 if (public.my_module_access(a)->>'check_price')::boolean then raise exception 'ASSERT grant revocation immediate'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 perform public.set_member_locations(m,array[a]);
 if (select version from public.store_module_access where membership_id=m and store_id=a) is distinct from 2 then raise exception 'ASSERT retained store permissions survive assignment edits'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee_id,'role','authenticated')::text,true);
 if app.has_module(b,'goods_out') then raise exception 'ASSERT membership removal takes priority'; end if;
 reset role;
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app_private' and has_function_privilege('authenticated',p.oid,'execute')) then raise exception 'ASSERT private RPC grants'; end if;
 raise exception 'TESTS_PASSED';
end $$;
