do $$
#variable_conflict use_variable
declare u uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();b uuid;s uuid;s2 uuid;wh uuid;p uuid;c uuid;o uuid;i uuid;mid uuid;take uuid;item uuid;stamp timestamptz;details jsonb;result jsonb;sid uuid:=gen_random_uuid();recurring uuid;version bigint;grants jsonb;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'oct-owner@test.invalid','{}'),(staff,'oct-staff@test.invalid','{}'),(outsider,'oct-other@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 result:=public.create_business('October workflows','Shop');b:=(result->>'business_id')::uuid;s:=(result->>'store_id')::uuid;s2:=public.create_location(b,'Second','store');wh:=public.create_location(b,'Warehouse','warehouse');
 p:=public.create_product(s,'Test item',null,null,null,50,100);perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10)));
 insert into public.customers(business_id,store_id,name) values(b,s,'Customer') returning id into c;perform public.set_billing_settings(b,15,true);
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),gen_random_uuid());perform public.process_sales_order(o,'confirm');
 i:=public.create_delivery_invoice(o,current_date+1,10,20);
 if not exists(select 1 from public.v_invoice_balances where id=i and subtotal=220 and discount=10 and tax_amount=31.5 and total=241.5 and delivery_fee=20) then raise exception 'ASSERT fee totals';end if;
 if (select sum(net_total) from public.sales_invoice_items where invoice_id=i)<>218.5 then raise exception 'ASSERT product returns exclude delivery fee';end if;
 if public.create_delivery_invoice(o,current_date+1,10,20)<>i then raise exception 'ASSERT fee retry';end if;
 begin perform public.create_delivery_invoice(o,current_date+1,10,21);raise exception 'ASSERT changed fee retry accepted';exception when others then if sqlerrm<>'REQUEST_CONFLICT' then raise;end if;end;
 perform public.issue_sales_invoice(i);
 perform public.amend_invoice_items(i,0,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),0,'Reduce goods',gen_random_uuid());
 if not exists(select 1 from public.sales_invoices where id=i and total=138 and delivery_fee=20 and subtotal=120) then raise exception 'ASSERT amendment preserves fee';end if;
 if (select sum(net_total) from public.sales_invoice_items where invoice_id=i)<>115 then raise exception 'ASSERT amended product return amount';end if;
 reset role;if (app_private.customer_invoice_document(i)->'details'->>'Delivery fee')::numeric<>20 then raise exception 'ASSERT email fee';end if;set local role authenticated;
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),gen_random_uuid());perform public.process_sales_order(o,'confirm');
 begin perform public.create_delivery_invoice(o,current_date+1,0,-1);raise exception 'ASSERT negative fee accepted';exception when others then if sqlerrm<>'INVALID_DELIVERY_FEE' then raise;end if;end;
 take:=public.start_stock_take(s);select id into item from public.stock_take_items where stock_take_id=take and product_id=p;
 if public.save_all_stock_take_counts(take,jsonb_build_array(jsonb_build_object('id',item,'quantity',8,'expected_at',null)))<>1 then raise exception 'ASSERT batch count';end if;
 if (select quantity from public.stock where product_id=p)<>10 then raise exception 'ASSERT saving counts changed stock';end if;
 select counted_at into stamp from public.stock_take_items where id=item;
 begin perform public.save_all_stock_take_counts(take,jsonb_build_array(jsonb_build_object('id',item,'quantity',7,'expected_at',null)));raise exception 'ASSERT stale count accepted';exception when others then if sqlerrm<>'COUNT_CHANGED_REFRESH' then raise;end if;end;
 if (select counted_qty from public.stock_take_items where id=item)<>8 then raise exception 'ASSERT stale count modified data';end if;
 perform public.complete_stock_take(take);if (select quantity from public.stock where product_id=p)<>8 then raise exception 'ASSERT approval applies count';end if;
 details:=jsonb_build_object('title','Schedule','customer_id',c,'frequency','MONTHLY','start_date',current_date,'next_date',current_date,'due_days',7,'terms','CASH','tax_percent',15,'recipient','','active',true,'auto_email',false,'items',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1,'unit_price',100)));
 perform public.save_recurring_invoice(s,sid,0,details);
 begin perform public.delete_recurring_invoice(sid,1);raise exception 'ASSERT active delete allowed';exception when others then if sqlerrm<>'DEACTIVATE_SCHEDULE_FIRST' then raise;end if;end;
 reset role;recurring:=app_private.generate_recurring_invoice(sid);set local role authenticated;
 select r.version into version from public.recurring_invoices r where id=sid;
 perform public.save_recurring_invoice(s,sid,version,details||jsonb_build_object('active',false,'next_date',current_date+interval '1 month'));
 select r.version into version from public.recurring_invoices r where id=sid;perform public.delete_recurring_invoice(sid,version);
 if exists(select 1 from public.recurring_invoices where id=sid) or not exists(select 1 from public.sales_invoices where id=recurring and recurring_schedule_id=sid) then raise exception 'ASSERT deletion lost historical invoice';end if;
 perform public.disable_warehouse(wh);
 if not exists(select 1 from jsonb_array_elements(public.warehouse_management(b)) x where x->>'location_id'=wh::text and x->>'is_active'='false') then raise exception 'ASSERT disabled warehouse missing';end if;
 perform public.enable_warehouse(wh);if not exists(select 1 from public.stores where id=wh and is_active) then raise exception 'ASSERT enable warehouse';end if;
 reset role;mid:=public.add_member_by_email(b,'oct-staff@test.invalid','employee');set local role authenticated;perform public.set_member_locations(mid,array[s,s2]);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 if exists(select 1 from jsonb_each(public.my_module_access(s)) e where e.value='true'::jsonb) then raise exception 'ASSERT new employee default access';end if;
 begin perform public.create_product(s,'Denied');raise exception 'ASSERT denied product creation';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 grants:='{"orders":true,"orders_new":true,"orders_recent":true,"stock_take":true,"stock_take_approve":true}';perform public.set_store_module_access(mid,s,grants,0);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 if not app.has_module(s,'orders_new') or not app.has_module(s,'stock_take_approve') or app.has_module(s2,'orders_new') or app.has_module(s,'access_control') then raise exception 'ASSERT individual store grants';end if;
 begin perform public.set_store_module_access(mid,s,'{"settings":true}',1);raise exception 'ASSERT self elevation';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 take:=public.start_stock_take(s);select id into item from public.stock_take_items where stock_take_id=take and product_id=p;perform public.save_stock_take_count(item,8);perform public.complete_stock_take(take);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);perform public.set_store_module_access(mid,s,'{}',1);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);if app.has_module(s,'orders_new') then raise exception 'ASSERT revocation immediate';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated')::text,true);
 if public.warehouse_management(b)<>'[]'::jsonb then raise exception 'ASSERT cross tenant warehouse';end if;
 begin perform public.enable_warehouse(wh);raise exception 'ASSERT cross tenant enable';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 reset role;
 if has_function_privilege('anon','public.create_delivery_invoice(uuid,date,numeric,numeric)','execute') or has_function_privilege('authenticated','app_private.create_sales_invoice(uuid,date,text,numeric,text,numeric)','execute') then raise exception 'ASSERT restricted RPC exposure';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
