do $$
declare u uuid:=gen_random_uuid(); b uuid;s uuid;s2 uuid;p uuid;link uuid;link2 uuid;req uuid:=gen_random_uuid();secret text:=repeat('a',64);result jsonb;o uuid;o2 uuid;i uuid;d uuid;blocked boolean;today date:=(now() at time zone 'Africa/Johannesburg')::date;v bigint;employee uuid:=gen_random_uuid();mid uuid;report jsonb;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'online-owner@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 result:=public.create_business('Online business','Online shop');b:=(result->>'business_id')::uuid;s:=(result->>'store_id')::uuid;
 s2:=public.create_location(b,'Other online shop','store','OS2');
 p:=public.create_product(s,'Online water','ONLINE-WATER',null,null,5,10);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10)));
 link:=(public.online_settings(s)->>'link_token')::uuid;link2:=(public.online_settings(s2)->>'link_token')::uuid;
 perform public.save_online_ordering_settings(s,1,'{"enabled":true,"collection_enabled":true,"delivery_enabled":true,"pay_on_collection":true,"delivery_fee":5,"payment_instructions":"Test bank instructions","reservation_hours":24,"notifications_enabled":true}');
 perform public.save_product_online(p,(select updated_at from public.products where id=p),'{"available_online":true,"online_price":"12","online_description":"Fresh water"}');
 reset role;
 blocked:=false;begin set local role anon;perform public.customer_catalog(link);exception when insufficient_privilege then blocked:=true;end;reset role;if not blocked then raise exception 'ASSERT anon cannot access service RPC';end if;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);set local role service_role;
 result:=public.customer_catalog(link);if (result->'products'->0->>'price')::numeric<>12 or result->'products'->0?'cost_price' or result->'products'->0?'quantity' then raise exception 'ASSERT private catalogue whitelist';end if;
 result:=public.place_customer_order(link,req,secret,'{"name":"Buyer","phone":"01234","email":"buyer@example.test","email_notifications":true}',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',3,'unit_price',0)),'COLLECTION',today,'PAY_ON_COLLECTION');o:=(result->>'order_id')::uuid;
 if public.place_customer_order(link,req,secret,'{"name":"Buyer","phone":"01234","email":"buyer@example.test","email_notifications":true}',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',3,'unit_price',0)),'COLLECTION',today,'PAY_ON_COLLECTION')<>result then raise exception 'ASSERT exact retry';end if;
 blocked:=false;begin perform public.customer_order_status(link,o,repeat('b',64));exception when others then if sqlerrm<>'ORDER_NOT_FOUND' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT private token';end if;
 blocked:=false;begin perform public.customer_order_status(link2,o,secret);exception when others then if sqlerrm<>'ORDER_NOT_FOUND' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cross-store tracking';end if;
 if (public.customer_order_status(link,o,secret)->>'total')::numeric<>36 then raise exception 'ASSERT price ignores customer price';end if;
 reset role;if app_private.online_reserved(p)<>3 or (select quantity from public.stock where product_id=p)<>10 then raise exception 'ASSERT stock reserved without movement';end if;
 blocked:=false;begin update public.stock set quantity=2 where product_id=p;exception when others then if sqlerrm<>'STOCK_RESERVED_ONLINE' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT POS stock protection';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 perform public.process_online_order(o,1,'ready','{}',gen_random_uuid());
 blocked:=false;begin perform public.process_online_order(o,2,'collect','{}',gen_random_uuid());exception when others then if sqlerrm<>'COLLECTION_PAYMENT_REQUIRED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT collect requires payment';end if;
 req:=gen_random_uuid();perform public.process_online_order(o,2,'confirm_payment','{"method":"CASH"}',req);perform public.process_online_order(o,2,'confirm_payment','{"method":"CASH"}',req);
 if (select status from public.online_orders where order_id=o)<>'READY_FOR_COLLECTION' then raise exception 'ASSERT payment preserves ready state';end if;
 perform public.process_online_order(o,3,'collect','{}',gen_random_uuid());
 if exists(select 1 from public.order_deliveries d join public.sales_invoices i on i.id=d.invoice_id where i.order_id=o) or (select quantity from public.stock where product_id=p)<>7 then raise exception 'ASSERT collected stock once, no delivery';end if;
 reset role;perform set_config('request.jwt.claims','{"role":"service_role"}',true);set local role service_role;
 result:=public.place_customer_order(link,gen_random_uuid(),secret,'{"name":"Deliver Buyer","phone":"01234","address":"10 Test Road","email":"delivery@example.test","email_notifications":true}',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),'DELIVERY',today,'BANK_TRANSFER');o2:=(result->>'order_id')::uuid;
 reset role;perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.process_online_order(o2,1,'ready','{}',gen_random_uuid());exception when others then if sqlerrm<>'PAYMENT_REQUIRED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT unpaid delivery cannot prepare';end if;
 blocked:=false;begin perform public.create_sales_invoice(o2,today,'CASH');exception when others then if sqlerrm<>'USE_ONLINE_ORDERS' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT invoice payment bypass';end if;
 reset role;
 insert into auth.users(id,email,raw_user_meta_data) values(employee,'online-processor@test.invalid','{}');
 insert into public.memberships(business_id,user_id,role) values(b,employee,'employee') returning id into mid;
 insert into public.store_memberships(membership_id,store_id,business_id) values(mid,s,b);
 insert into public.store_module_access(membership_id,store_id,permissions) values(mid,s,'{"orders":false,"orders_online":true,"orders_online_process":true}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);set local role authenticated;
 perform public.process_online_order(o2,1,'confirm_payment','{"method":"CARD_EFT"}',gen_random_uuid());
 reset role;
 select invoice_id into i from public.online_orders where order_id=o2;select id into d from public.order_deliveries where invoice_id=i;
 if d is null or (select total from public.sales_invoices where id=i)<>29 then raise exception 'ASSERT shared delivery and fee';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);set local role authenticated;
 perform public.process_online_order(o2,2,'tracking','{"courier_company":"Courier","tracking_number":"TRACK123","tracking_url":"https://example.test/track/123"}',gen_random_uuid());
 perform public.process_online_order(o2,3,'release_delivery','{}',gen_random_uuid());
 reset role;perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 perform public.process_delivery(d,1,'dispatch','{}',gen_random_uuid());perform public.process_delivery(d,2,'complete','{"received_by":"Buyer"}',gen_random_uuid());
 report:=public.online_orders_report(s,today,today);
 if (report->'metrics'->>'total_orders')::int<>2 or (report->'metrics'->>'paid_value')::numeric<>65 or (report->'metrics'->>'delivery_fees')::numeric<>5 or (report->'metrics'->>'completed_orders')::int<>2 or (report->'products'->0->>'quantity')::numeric<>5 then raise exception 'ASSERT populated online report totals: %',report;end if;
 reset role;report:=app_private.scheduled_report_data(s,'DAILY_SALES',today,today);
 if (report->'metrics'->>'total_sales')::numeric<>65 or (report->'metrics'->>'cash')::numeric<>36 or (report->'metrics'->>'card_eft')::numeric<>29 then raise exception 'ASSERT daily invoice/payment totals: %',report;end if;
 report:=app_private.scheduled_report_data(s,'BUSINESS_PERFORMANCE',today,today);
 if (report->'metrics'->>'total_sales')::numeric<>65 then raise exception 'ASSERT no double counted business invoice sales: %',report;end if;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);set local role service_role;
 if public.customer_order_status(link,o2,secret)->>'status'<>'DELIVERED' then raise exception 'ASSERT public delivery tracking';end if;
 result:=public.place_customer_order(link,gen_random_uuid(),secret,'{"name":"Expiry Buyer","phone":"01234"}',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),'COLLECTION',today,'PAY_ON_COLLECTION');o2:=(result->>'order_id')::uuid;
 reset role;update public.online_orders set expires_at=now()-interval '1 second' where order_id=o2;perform app_private.expire_online_orders();
 if (select status from public.online_orders where order_id=o2)<>'EXPIRED' or app_private.online_reserved(p)<>0 then raise exception 'ASSERT expiry releases stock';end if;
 set constraints all immediate;set constraints all deferred;
 if not exists(select 1 from public.customer_document_notifications where system_online and document->>'summary'='Payment Confirmed') then raise exception 'ASSERT payment notification';end if;
 if not exists(select 1 from public.customer_document_notifications where system_online and document->>'tracking_url' like '%#'||secret) then raise exception 'ASSERT private tracking email';end if;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 result:=public.claim_customer_documents(5);
 if jsonb_array_length(result)=0 then raise exception 'ASSERT system online emails claimed';end if;
 result:=public.place_customer_order(link,gen_random_uuid(),secret,'{"name":"Cancel Buyer","phone":"01234","email":"cancel@example.test","email_notifications":true}',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),'COLLECTION',today,'PAY_ON_COLLECTION');o2:=(result->>'order_id')::uuid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 perform public.process_online_order(o2,1,'cancel','{"reason":"Customer requested cancellation"}',gen_random_uuid());
 reset role;set constraints all immediate;set constraints all deferred;
 if (select count(*) from public.customer_document_notifications where customer_id=(select customer_id from public.sales_orders where id=o2) and document->>'summary' in ('CANCELLED','Customer requested cancellation'))<>1 then raise exception 'ASSERT one cancellation notification';end if;
 raise exception 'TESTS_PASSED';
end $$;
