do $$
declare u uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); biz uuid; loc uuid; member uuid;
  res jsonb; c uuid; p uuid; oid uuid; iid uuid; blocked boolean; req uuid;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(u,'workflow-owner@test.invalid','{}'),(employee,'workflow-employee@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true); set local role authenticated;
  res:=public.create_business('Workflow test','Shop'); biz:=(res->>'business_id')::uuid; loc:=(res->>'store_id')::uuid;
  member:=public.add_member_by_email(biz,'workflow-employee@test.invalid','employee'); perform public.set_member_locations(member,array[loc]);
  insert into public.customers(business_id,store_id,name) values(biz,loc,'Customer') returning id into c;
  p:=public.create_product(loc,'Product','WORKFLOW-1',null,null,5,10);
  perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10)));
  oid:=public.create_sales_order(loc,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),gen_random_uuid());
  if public.order_workflow_summary(loc)->0->>'status'<>'DRAFT' then raise exception 'ASSERT draft'; end if;
  perform public.process_sales_order(oid,'confirm'); iid:=public.create_sales_invoice(oid,current_date,'CASH');
  if public.order_workflow_summary(loc)->0->>'status'<>'INVOICED' then raise exception 'ASSERT linked invoice'; end if;
  perform public.issue_sales_invoice(iid);
  perform public.post_invoice_entry(iid,'PAYMENT',4,gen_random_uuid(),'CASH');
  if (public.order_workflow_summary(loc)->0->'invoice'->>'outstanding')::numeric<>6 then raise exception 'ASSERT partial'; end if;
  req:=gen_random_uuid(); perform public.post_invoice_entry(iid,'PAYMENT',6,req,'CASH');
  perform public.post_invoice_entry(iid,'PAYMENT',6,req,'CASH');
  if public.order_workflow_summary(loc)->0->>'status'<>'READY_FOR_COLLECTION' then raise exception 'ASSERT ready'; end if;
  perform public.issue_invoice_goods(iid);
  if public.order_workflow_summary(loc)->0->>'status'<>'COMPLETED' then raise exception 'ASSERT completed'; end if;
  if (public.order_workflow_summary(loc)->0->>'can_cancel')::boolean then raise exception 'ASSERT no completed cancellation'; end if;
  blocked:=false; begin perform public.post_invoice_entry(iid,'PAYMENT',1,gen_random_uuid(),'CASH'); exception when others then if sqlerrm<>'PAYMENT_EXCEEDS_OUTSTANDING' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT no extra payment'; end if;
  perform public.post_invoice_entry(iid,'DEBIT_NOTE',2,gen_random_uuid(),null,null,'Approved correction');
  if public.order_workflow_summary(loc)->0->>'status'<>'AWAITING_PAYMENT' then raise exception 'ASSERT adjustment reopens balance'; end if;
  perform public.post_invoice_entry(iid,'PAYMENT',2,gen_random_uuid(),'CASH');
  -- Orders-only employee can see this limited summary, not the full invoice API.
  perform public.set_store_module_access(member,loc,'{"invoices":false,"reports":false,"returns":false,"credit":false}',0);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
  if public.order_workflow_summary(loc)->0->>'status'<>'COMPLETED' then raise exception 'ASSERT orders-only summary'; end if;
  if exists(select 1 from public.sales_invoices where id=iid) then raise exception 'ASSERT invoice access not widened'; end if;
  blocked:=false; begin perform public.order_workflow_summary(gen_random_uuid()); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT cross-store denied'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  perform public.set_store_module_access(member,loc,'{"orders":false}',1);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
  blocked:=false; begin perform public.order_workflow_summary(loc); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT revoked orders denied'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  perform public.set_credit_limit(c,100);
  oid:=public.create_sales_order(loc,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),gen_random_uuid());
  perform public.process_sales_order(oid,'confirm'); iid:=public.create_sales_invoice(oid,current_date,'CREDIT');
  perform public.issue_sales_invoice(iid); perform public.issue_invoice_goods(iid);
  select value into res from jsonb_array_elements(public.order_workflow_summary(loc)) where value->>'id'=oid::text;
  if res->>'status'<>'AWAITING_PAYMENT' then raise exception 'ASSERT credit collection before payment'; end if;
  perform public.post_invoice_entry(iid,'PAYMENT',10,gen_random_uuid(),'CASH');
  select value into res from jsonb_array_elements(public.order_workflow_summary(loc)) where value->>'id'=oid::text;
  if res->>'status'<>'COMPLETED' then raise exception 'ASSERT credit order completed on settlement'; end if;
  raise exception 'TESTS_PASSED';
end $$;
