do $$
declare u uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();b uuid;s uuid;c uuid;p uuid;q uuid;o uuid;i uuid;d uuid;req uuid;rid uuid;x jsonb;blocked boolean;v bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'order-revision@test.invalid','{}'),(outsider,'order-revision-outside@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 x:=public.create_business('Revision business','Revision store');b:=(x->>'business_id')::uuid;s:=(x->>'store_id')::uuid;
 insert into public.customers(business_id,store_id,name,phone,address,email,email_notifications) values(b,s,'Receiver','0112345678','10 Main Road','receiver@test.invalid',true) returning id into c;
 p:=public.create_product(s,'Unavailable product','REVISION-P',null,null,5,10);
 q:=public.create_product(s,'Replacement product','REVISION-Q',null,null,10,20);
 perform public.receive_stock(s,null,null,null,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',20)));
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),gen_random_uuid());
 perform public.process_sales_order(o,'confirm');i:=public.create_delivery_invoice(o,current_date+1,0);
 if public.create_delivery_invoice(o,current_date+1,0)<>i then raise exception 'ASSERT retry invoice';end if;
 select id,version into d,v from public.order_deliveries where invoice_id=i;
 if d is null or (select status from public.order_deliveries where id=d)<>'CREATED' or (select scheduled_date from public.order_deliveries where id=d) is not null then raise exception 'ASSERT created before payment without invented date';end if;
 if jsonb_array_length(public.delivery_page(s,'created')->'rows')<>1 or jsonb_array_length(public.delivery_page(s,'scheduled')->'rows')<>0 then raise exception 'ASSERT created separate queue';end if;
 if public.order_workflow_summary(s)->0->>'status'<>'DELIVERY_CREATED' then raise exception 'ASSERT order created status';end if;
 if (public.delivery_report(array[s],'{"status":"CREATED"}')->'summary'->>'created')::int<>1 then raise exception 'ASSERT created report';end if;
 blocked:=false;begin perform public.process_delivery(d,v,'dispatch','{}',gen_random_uuid());exception when others then if sqlerrm<>'DELIVERY_PAYMENT_REQUIRED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT unpaid dispatch blocked';end if;
 perform public.issue_sales_invoice(i);perform public.post_invoice_entry(i,'PAYMENT',20,gen_random_uuid(),'CASH');
 blocked:=false;begin perform public.issue_invoice_goods(i);exception when others then blocked:=true;end;if not blocked then raise exception 'ASSERT stock shortage';end if;
 req:=gen_random_uuid();rid:=public.amend_invoice_items(i,0,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',2)),0,'Replace unavailable product',req);
 if rid<>public.amend_invoice_items(i,0,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',2)),0,'Replace unavailable product',req) then raise exception 'ASSERT amendment idempotent';end if;
 if not exists(select 1 from public.v_invoice_balances where id=i and total=40 and paid=20 and outstanding=20 and revision=1) then raise exception 'ASSERT payment retained and increased outstanding';end if;
 if (select balance from public.credit_accounts where customer_id=c)<>20 then raise exception 'ASSERT customer ledger increased';end if;
 if (select product_id from public.order_current_items(o))<>q then raise exception 'ASSERT current order items';end if;
 if (public.delivery_detail(o)->'delivery'->'snapshot'->'items'->0->>'product_id')::uuid<>q then raise exception 'ASSERT revised delivery note';end if;
 if (select quantity from public.stock where product_id=q)<>20 then raise exception 'ASSERT no stock moved on amendment';end if;
 if (public.invoice_revision_history(i)->0->'before_data'->'invoice'->>'total')::numeric<>20 then raise exception 'ASSERT original invoice retained';end if;
 blocked:=false;begin perform public.amend_invoice_items(i,0,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',1)),0,'Stale editor',gen_random_uuid());exception when others then if sqlerrm<>'INVOICE_CHANGED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT stale editor';end if;
 -- Lowering the value does not erase payment or silently refund cash.
 perform public.amend_invoice_items(i,1,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',0.5)),0,'Reduce quantity',gen_random_uuid());
 if not exists(select 1 from public.v_invoice_balances where id=i and total=10 and paid=20 and outstanding=-10) or (select balance from public.credit_accounts where customer_id=c)<>-10 then raise exception 'ASSERT overpayment becomes recorded credit';end if;
 if (select count(*) from public.invoice_entries where invoice_id=i and kind='PAYMENT')<>1 then raise exception 'ASSERT payments immutable';end if;
 x:=public.invoice_monthly_reconciliation(s,current_date);
 if (x->>'closing')::numeric<>-10 or (x->>'revisions')::numeric<>-10 or (x->>'customer_ledger_balance')::numeric<>-10 then raise exception 'ASSERT invoice and customer reconciliation agrees after revisions: %',x;end if;
 x:=public.invoice_monthly_reconciliation(s,current_date);
 if (x->>'closing')::numeric<>-10 or (x->>'revisions')::numeric<>-10 or (x->>'customer_ledger_balance')::numeric<>-10 then raise exception 'ASSERT invoice and customer reconciliation agrees after revisions: %',x;end if;
 set constraints all immediate;set constraints all deferred;
 if not exists(select 1 from public.customer_document_notifications where customer_id=c and document->>'type'='Revised invoice') then raise exception 'ASSERT corrected invoice notification';end if;
 select version into v from public.order_deliveries where id=d;
 perform public.process_delivery(d,v,'schedule',jsonb_build_object('date',current_date+1),gen_random_uuid());
 if jsonb_array_length(public.delivery_page(s,'created')->'rows')<>0 or jsonb_array_length(public.delivery_page(s,'scheduled')->'rows')<>1 then raise exception 'ASSERT scheduled leaves created';end if;
 perform public.issue_invoice_goods(i);
 blocked:=false;begin perform public.amend_invoice_items(i,2,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',1)),0,'After release',gen_random_uuid());exception when others then if sqlerrm<>'INVOICE_AMENDMENT_CLOSED' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT released immutable';end if;
 if (select quantity from public.stock where product_id=q)<>19.5 then raise exception 'ASSERT corrected stock released exactly once';end if;
 select version into v from public.order_deliveries where id=d;
 perform public.process_delivery(d,v,'dispatch','{}',gen_random_uuid());perform public.process_delivery(d,v+1,'complete','{"received_by":"Recipient"}',gen_random_uuid());
 -- Draft invoice cancellation automatically removes Created from outstanding queues.
 o:=public.create_sales_order(s,c,jsonb_build_array(jsonb_build_object('product_id',q,'quantity',1)),gen_random_uuid());perform public.process_sales_order(o,'confirm');i:=public.create_delivery_invoice(o,current_date+1,0);
 perform public.cancel_sales_invoice(i,'Customer cancelled');
 if not exists(select 1 from public.order_deliveries where invoice_id=i and status='CANCELLED') then raise exception 'ASSERT draft cancellation propagates';end if;
 if not exists(select 1 from jsonb_array_elements(public.order_workflow_summary(s))summary where summary->>'id'=o::text and summary->>'status'='INVOICE_CANCELLED') then raise exception 'ASSERT invoice cancelled label';end if;
 if jsonb_array_length(public.delivery_page(s,'created')->'rows')<>0 then raise exception 'ASSERT cancelled leaves created';end if;
 reset role;perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.invoice_revision_history(i);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT revision tenant isolation';end if;
 blocked:=false;begin perform public.order_current_items(o);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT order tenant isolation';end if;
 if exists(select 1 from public.invoice_revisions) then raise exception 'ASSERT revision RLS';end if;
 blocked:=false;begin perform public.amend_invoice_items(i,0,'[]',0,'Denied',gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cross tenant mutation';end if;
 blocked:=false;begin perform public.amend_invoice_items(i,0,'[]',0,'Denied',gen_random_uuid());exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;if not blocked then raise exception 'ASSERT cross tenant mutation';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
