do $$
declare u uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); r jsonb; biz uuid; loc uuid; wh uuid; food uuid; normal uuid; pack uuid; wp uuid; wu uuid; sale uuid; li uuid; ret uuid; conv uuid; t uuid; v jsonb; request uuid:=gen_random_uuid(); take uuid; report record; count_before int; own_shift uuid; other_shift uuid; customer uuid; invoice uuid; order_id uuid; submission uuid; cash_day date:=(now() at time zone 'Africa/Johannesburg')::date;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'tracking-owner@test.invalid','{}'),(staff,'tracking-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 r:=public.create_business('Tracking tests','Shop');biz:=(r->>'business_id')::uuid;loc:=(r->>'store_id')::uuid;wh:=public.create_location(biz,'Warehouse','warehouse');
 food:=public.create_product_catalog(loc,'KOTA','{"cost":10,"selling":35,"tracking_type":"SALES_ONLY"}');
 if (select stock_status from public.v_product_catalog where id=food)<>'not_tracked' then raise exception 'ASSERT sales-only status';end if;
 sale:=public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',2)),p_request:=request);
 if public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',2)),p_request:=request)<>sale then raise exception 'ASSERT sale retry';end if;
 if (select total_amount from public.goods_out where id=sale)<>70 or (select quantity from public.stock where product_id=food)<>0 or exists(select 1 from public.stock_movements where product_id=food) then raise exception 'ASSERT sale without stock movement';end if;
 select * into report from public.quantity_sales_report(loc,null,null,food,u,'SALES_ONLY');
 if report.sold_qty<>2 or report.net_qty<>2 or report.revenue<>70 then raise exception 'ASSERT sales report';end if;
 select id into li from public.goods_out_items where goods_out_id=sale;
 ret:=public.submit_goods_return('sale',sale,jsonb_build_array(jsonb_build_object('item_id',li,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK')),'Unwanted','Checked',gen_random_uuid());
 perform public.process_goods_return(ret,true);perform public.record_customer_refund(ret,35,'CASH','Refund',gen_random_uuid());
 select * into report from public.quantity_sales_report(loc,null,null,food,u,'SALES_ONLY');
 if report.sold_qty<>2 or report.returned_qty<>1 or report.net_qty<>1 or report.revenue<>35 then raise exception 'ASSERT net report';end if;
 if exists(select 1 from public.stock_batches where product_id=food) or exists(select 1 from public.stock_movements where product_id=food) or (select quantity from public.stock where product_id=food)<>0 then raise exception 'ASSERT return without physical stock';end if;
 if (select count(*) from public.quantity_sales_report(loc,current_date-3,current_date-1,food,u,'SALES_ONLY') where sold_qty<>0)<>0 then raise exception 'ASSERT report dates';end if;
 begin perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',5)));raise exception 'ASSERT sales-only receipt blocked';exception when others then if sqlerrm<>'SALES_ONLY_NO_STOCK' then raise;end if;end;
 normal:=public.create_product_catalog(loc,'Juice','{"barcode":"TRACK-JUICE","cost":2,"selling":3,"bulk_enabled":true,"units_per_pack":12,"bulk_unit":"case"}');
 select pack_product_id,id into pack,conv from public.bulk_conversions where unit_product_id=normal;
 if pack is null or (select bulk_parent_id from public.products where id=pack)<>normal or (select sku from public.products where id=pack) is not null or (select quantity from public.stock where product_id=pack)<>0 then raise exception 'ASSERT dependent zero bulk';end if;
 if jsonb_array_length((select bulk_options from public.v_product_catalog where id=normal))<>1 then raise exception 'ASSERT linked catalogue';end if;
 v:='{"name":"Juice","cost_price":2,"selling_price":3,"min_stock_level":0,"reorder_level":0,"unit":"each","track_expiry":false,"is_active":true,"bulk_enabled":true,"units_per_pack":12,"bulk_unit":"case"}';
 perform public.save_product_details(normal,v);perform public.save_product_details(normal,v);
 if (select count(*) from public.products where bulk_parent_id=normal)<>1 then raise exception 'ASSERT repeated configure no duplicates';end if;
 begin perform public.complete_sale(loc,'CASH',null,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',1),jsonb_build_object('product_id',normal,'quantity',1)));raise exception 'ASSERT mixed stock guard';exception when others then if sqlerrm not like 'INSUFFICIENT_STOCK%' then raise;end if;end;
 if (select count(*) from public.goods_out where store_id=loc)<>1 then raise exception 'ASSERT failed mixed sale rolled back';end if;

 insert into public.customers(business_id,store_id,name) values(biz,loc,'Food invoice customer') returning id into customer;
 begin perform public.complete_sale(loc,'CREDIT',customer,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',1)));raise exception 'ASSERT credit control retained';exception when others then if sqlerrm not like 'CREDIT_LIMIT_EXCEEDED%' then raise;end if;end;
 order_id:=public.create_sales_order(loc,customer,jsonb_build_array(jsonb_build_object('product_id',food,'quantity',3)),gen_random_uuid());perform public.process_sales_order(order_id,'confirm');invoice:=public.create_sales_invoice(order_id,current_date+30,'CASH');perform public.issue_sales_invoice(invoice);
 begin perform public.issue_invoice_goods(invoice);raise exception 'ASSERT invoice payment control';exception when others then if sqlerrm<>'INVOICE_PAYMENT_REQUIRED' then raise;end if;end;
 perform public.post_invoice_entry(invoice,'PAYMENT',105,gen_random_uuid(),'CASH');perform public.issue_invoice_goods(invoice);
 select * into report from public.quantity_sales_report(loc,null,null,food,u,'SALES_ONLY');
 if report.sold_qty<>5 or report.net_qty<>4 or report.revenue<>140 or exists(select 1 from public.stock_movements where product_id=food) then raise exception 'ASSERT invoice sales counted without stock';end if;
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',pack,'quantity',3)));
 perform public.unpack_stock(conv,2,'Shelf',gen_random_uuid());
 if (select quantity from public.stock where product_id=pack)<>1 or (select quantity from public.stock where product_id=normal)<>24 then raise exception 'ASSERT linked unpack';end if;
 begin perform public.save_product_details(normal,v||'{"bulk_enabled":false}');raise exception 'ASSERT cannot disable stocked bulk';exception when others then if sqlerrm<>'BULK_STOCK_OR_TRANSFER_REMAINS' then raise;end if;end;
 perform public.sync_warehouse_products(wh,loc,false);select id into wu from public.products where store_id=wh and name='Juice';
 if exists(select 1 from public.products where store_id=wh and name='KOTA') then raise exception 'ASSERT warehouse sync excludes sales-only';end if;
 perform public.save_product_details(wu,v);select pack_product_id into wp from public.bulk_conversions where unit_product_id=wu;
 perform public.receive_stock(wh,null,null,null,jsonb_build_array(jsonb_build_object('product_id',wp,'quantity',4)));
 t:=public.save_warehouse_transfer(wh,loc,jsonb_build_array(jsonb_build_object('source_product_id',wp,'quantity',2)),gen_random_uuid());perform public.submit_warehouse_transfer(t);
 if (select quantity from public.stock where product_id=wp)<>2 or (select quantity from public.stock where product_id=pack)<>1 then raise exception 'ASSERT bulk transit';end if;
 perform public.process_stock_transfer(t,'receive');
 if (select quantity from public.stock where product_id=pack)<>3 or (select quantity from public.stock where product_id=normal)<>24 then raise exception 'ASSERT received remains bulk';end if;
 take:=public.start_stock_take(loc);
 if exists(select 1 from public.stock_take_items where stock_take_id=take and product_id=food) then raise exception 'ASSERT counts exclude sales-only';end if;
 begin perform public.save_product_details(food,'{"name":"KOTA","cost_price":10,"selling_price":35,"min_stock_level":0,"reorder_level":0,"unit":"each","track_expiry":false,"is_active":true,"tracking_type":"QUANTITY"}');raise exception 'ASSERT historical tracking locked';exception when others then if sqlerrm<>'TRACKING_CHANGE_HAS_HISTORY_OR_STOCK' then raise;end if;end;
 reset role;insert into public.memberships(business_id,user_id,role) values(biz,staff,'employee');insert into public.store_memberships(business_id,store_id,membership_id) select biz,loc,id from public.memberships where business_id=biz and user_id=staff;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);set local role authenticated;
 begin perform public.save_product_details(normal,v);raise exception 'ASSERT employee cannot configure';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;

 own_shift:=public.open_cash_up(loc,cash_day-1,20);
 r:=public.cash_up_summary(loc,cash_day-1);
 if r->'day_activity'<>'null'::jsonb or (r->'session'->>'created_by')::uuid<>staff then raise exception 'ASSERT own cash shift';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 other_shift:=public.open_cash_up(loc,cash_day,50);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 if exists(select 1 from public.cash_ups where id=other_shift) then raise exception 'ASSERT other shift RLS';end if;
 begin perform public.cash_up_summary(loc,cash_day);raise exception 'ASSERT other shift summary denied';exception when others then if sqlerrm<>'SHIFT_BELONGS_TO_OTHER_USER' then raise;end if;end;
 begin perform public.submit_cash_up(other_shift,50,'{}','fake','',gen_random_uuid());raise exception 'ASSERT other shift count denied';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 begin perform public.record_cash_movement(loc,cash_day,'REMOVE',1,'Unauthorized',gen_random_uuid());raise exception 'ASSERT cashier banking denied';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;

 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 r:=public.cash_up_summary(loc,cash_day);submission:=public.submit_cash_up(other_shift,(r->>'expected')::numeric,'{}',r->>'count_token','',gen_random_uuid());perform public.review_cash_up(other_shift,submission,'APPROVE','');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 r:=public.cash_up_summary(loc,cash_day);
 if not(r ? 'handover') or r ? 'sources' or r ? 'history' then raise exception 'ASSERT minimal approved handover';end if;
 own_shift:=public.start_next_cash_shift(other_shift,(r->'handover'->>'counted')::numeric,'',gen_random_uuid());r:=public.cash_up_summary(loc,cash_day);
 if (r->'session'->>'created_by')::uuid<>staff or jsonb_array_length(r->'shifts')<>1 or r->'sources' ? 'cumulative' then raise exception 'ASSERT own new shift and privacy';end if;
 if (r->'sources'->'activity'->>'total_sales')::numeric<>0 then raise exception 'ASSERT total sales resets at handover';end if;
 reset role;if has_function_privilege('anon','public.quantity_sales_report(uuid,date,date,uuid,uuid,text)','execute') then raise exception 'ASSERT anonymous report blocked';end if;
 raise exception 'TESTS_PASSED';
end $$;
