do $$
declare u uuid:=gen_random_uuid(); cashier uuid:=gen_random_uuid(); biz uuid; loc uuid; c uuid; p uuid; member uuid; res jsonb;
  oid uuid; iid uuid; line uuid; rid uuid; rid2 uuid; fid uuid; req uuid; payload jsonb; blocked boolean; sale uuid; q numeric;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(u,'returns-owner@test.invalid','{}'),(cashier,'returns-cashier@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true); set local role authenticated;
  res:=public.create_business('Returns test','Shop'); biz:=(res->>'business_id')::uuid; loc:=(res->>'store_id')::uuid;
  reset role; member:=public.add_member_by_email(biz,'returns-cashier@test.invalid','employee'); set local role authenticated; perform public.set_member_locations(member,array[loc]);
  insert into public.customers(business_id,store_id,name) values(biz,loc,'Return customer') returning id into c;
  p:=public.create_product(loc,'Milk','RET-MILK',null,null,5,10,0,0,'each',true);
  perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10,'expiry_date','2028-01-01')));
  oid:=public.create_sales_order(loc,c,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',4)),gen_random_uuid());
  perform public.process_sales_order(oid,'confirm'); iid:=public.create_sales_invoice(oid,current_date+30,'CASH'); perform public.issue_sales_invoice(iid);
  perform public.post_invoice_entry(iid,'PAYMENT',40,gen_random_uuid(),'CASH'); perform public.issue_invoice_goods(iid);
  select id into line from public.sales_invoice_items where invoice_id=iid;
  payload:=jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK','expiry_date','2028-01-01'));
  perform set_config('request.jwt.claims',jsonb_build_object('sub',cashier,'role','authenticated')::text,true);
  req:=gen_random_uuid(); rid:=public.submit_goods_return('invoice',iid,payload,'Unwanted','Sealed, inspected',req);
  if rid<>public.submit_goods_return('invoice',iid,payload,'Unwanted','Sealed, inspected',req) then raise exception 'ASSERT return retry'; end if;
  if (select quantity from public.stock where product_id=p)<>6 then raise exception 'ASSERT submitted return does not enter stock'; end if;
  blocked:=false; begin perform public.process_goods_return(rid,true); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT return requires approval'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  perform public.process_goods_return(rid,true); perform public.process_goods_return(rid,true);
  if (select quantity from public.stock where product_id=p)<>7 then raise exception 'ASSERT approved restock once'; end if;
  if (select balance from public.credit_accounts where customer_id=c)<>-10 then raise exception 'ASSERT paid return creates account credit'; end if;
  req:=gen_random_uuid(); fid:=public.record_customer_refund(rid,10,'CASH','Refund returned goods',req);
  if fid<>public.record_customer_refund(rid,10,'CASH','Refund returned goods',req) then raise exception 'ASSERT refund retry'; end if;
  if (select balance from public.credit_accounts where customer_id=c)<>0 then raise exception 'ASSERT refund consumes account credit'; end if;
  blocked:=false; begin perform public.record_customer_refund(rid,1,'CASH','Excess',gen_random_uuid()); exception when others then if sqlerrm<>'REFUND_EXCEEDS_AVAILABLE_CREDIT' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT refund cap'; end if;
  payload:=jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','DAMAGED','action','QUARANTINE'));
  rid2:=public.submit_goods_return('invoice',iid,payload,'Damaged: seal','Needs manager inspection',gen_random_uuid()); perform public.process_goods_return(rid2,true);
  if (select quantity from public.stock where product_id=p)<>7 then raise exception 'ASSERT quarantine not saleable'; end if;
  select id into line from public.goods_return_items where return_id=rid2;
  perform public.resolve_return_quarantine(line,'RETURN_TO_STOCK','Packaging checked, safe','2028-01-01');
  perform public.resolve_return_quarantine(line,'RETURN_TO_STOCK','Packaging checked, safe','2028-01-01');
  if (select quantity from public.stock where product_id=p)<>8 then raise exception 'ASSERT quarantine resolution once'; end if;
  select id into line from public.sales_invoice_items where invoice_id=iid;
  blocked:=false; begin perform public.submit_goods_return('invoice',iid,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',3,'condition','GOOD','action','WRITE_OFF')),'Other: Excess','Checked',gen_random_uuid()); exception when others then if sqlerrm<>'RETURN_EXCEEDS_SOLD_QUANTITY' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT return quantity cap'; end if;
  blocked:=false; begin perform public.submit_goods_return('invoice',iid,jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','EXPIRED','action','RETURN_TO_STOCK','expiry_date','2020-01-01')),'Expired','Checked',gen_random_uuid()); exception when others then if sqlerrm<>'RETURN_REQUIRES_QUARANTINE' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT expired cannot restock'; end if;
  -- Existing checkout sales also support tied returns and refunds.
  sale:=public.complete_sale(loc,'CARD_EFT',null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
  select id into line from public.goods_out_items where goods_out_id=sale;
  payload:=jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','DAMAGED','action','SUPPLIER_RETURN'));
  blocked:=false; begin perform public.submit_goods_return('sale',sale,payload,'Unknown reason','Inspected',gen_random_uuid()); exception when others then if sqlerrm<>'RETURN_REASON_NOT_CONFIGURED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT configured return reason required'; end if;
  blocked:=false; begin perform public.submit_goods_return('sale',sale,payload,'Other','Inspected',gen_random_uuid()); exception when others then if sqlerrm<>'RETURN_REASON_DETAIL_REQUIRED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT other requires detail'; end if;
  blocked:=false; begin perform public.set_return_reasons(biz,array['Faulty','faulty']); exception when others then if sqlerrm<>'INVALID_RETURN_REASONS' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT reason duplicates denied'; end if;
  perform public.set_return_reasons(biz,array['Faulty','Other']);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',cashier,'role','authenticated')::text,true);
  blocked:=false; begin perform public.set_return_reasons(biz,array['Anything']); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT reason settings owner only'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  perform public.set_billing_settings(biz,0,false);
  if (select return_reasons from public.billing_settings where business_id=biz)<>array['Faulty','Other'] then raise exception 'ASSERT billing settings preserve reasons'; end if;
  req:=gen_random_uuid(); rid:=public.submit_goods_return('sale',sale,payload,'Faulty','Supplier defect',req);
  perform public.set_return_reasons(biz,array['Other']);
  if rid<>public.submit_goods_return('sale',sale,payload,'Faulty','Supplier defect',req) then raise exception 'ASSERT existing return retry survives reason configuration change'; end if;
  if (select status from public.goods_returns where id=rid)<>'APPROVED' then raise exception 'ASSERT configured autoapproval'; end if;
  perform public.record_customer_refund(rid,10,'CARD_EFT','Reversal',gen_random_uuid(),'REVERSAL-1');
  if (select refunded from public.v_return_report where id=rid)<>10 or (select items from public.v_return_report where id=rid) not like '%Milk%' then raise exception 'ASSERT returned item and refund report';end if;
  if (select quantity from public.stock where product_id=p)<>7 then raise exception 'ASSERT supplier return does not add saleable stock'; end if;
  if exists(select 1 from public.reconcile_stock(loc) where diff<>0) then raise exception 'ASSERT returns stock reconciles'; end if;
  select sum(amount) into q from public.credit_transactions where business_id=biz;
  if q<>(select balance from public.credit_accounts where customer_id=c) then raise exception 'ASSERT returns customer reconciliation'; end if;
  if (select sum(quantity) from public.stock_batches where product_id=p)<>7 then raise exception 'ASSERT return expiry balance'; end if;
  reset role; raise exception 'TESTS_PASSED';
end $$;
