do $$
declare u uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); r jsonb; biz uuid; loc uuid; wh uuid; otherloc uuid; m uuid; p uuid; target uuid; t uuid; req uuid:=gen_random_uuid(); sale uuid; c uuid; line uuid; ret uuid; b uuid; before_qty numeric; blocked boolean; payload jsonb;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'sep13-owner@test.invalid','{}'),(staff,'sep13-staff@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 r:=public.create_business('September 13','Shop');biz:=(r->>'business_id')::uuid;loc:=(r->>'store_id')::uuid;
 wh:=public.create_location(biz,'Warehouse','warehouse');otherloc:=public.create_location(biz,'Other store','store');
 reset role;m:=public.add_member_by_email(biz,'sep13-staff@test.invalid','employee');set local role authenticated;
 perform public.set_member_locations(m,array[loc]);
 p:=public.create_product_catalog(wh,'Warehouse milk','{"sku":"WH-SKU","cost":5,"selling":10,"track_expiry":true}');
 target:=public.create_product_catalog(loc,'Shop milk','{"sku":"SHOP-SKU","cost":5,"selling":10,"track_expiry":true}');
 if not exists(select 1 from public.v_product_catalog where id=target and search_text ilike '%SHOP-SKU%') then raise exception 'ASSERT SKU searchable';end if;
 perform public.receive_stock(wh,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',10,'expiry_date',current_date+365)));
 perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',target,'quantity',2,'expiry_date',current_date+365)));
 t:=public.create_stock_transfer(wh,loc,jsonb_build_array(jsonb_build_object('source_product_id',p,'destination_product_id',target,'quantity',4)),req);
 perform public.process_stock_transfer(t,'submit');perform public.process_stock_transfer(t,'dispatch');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 if app.has_module(loc,'goods_in_new_stock') or app.has_module(loc,'goods_in_receive_transfer') then raise exception 'ASSERT employee default denial';end if;
 blocked:=false;begin perform public.process_stock_transfer(t,'receive');exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT receive grant required';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 perform public.set_store_module_access(m,loc,'{"goods_in_receive_transfer":true,"operations":false}',0);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 if not exists(select 1 from public.transfer_history(biz) where id=t) then raise exception 'ASSERT destination-only history';end if;
 if (public.transfer_detail(t)->>'source')<>'Warehouse' then raise exception 'ASSERT receive details';end if;
 if not exists(select 1 from public.stock_transfer_items where transfer_id=t) then raise exception 'ASSERT immutable lines visible';end if;
 if exists(select 1 from public.stock where store_id=wh) or exists(select 1 from public.warehouse_summary(biz)) then raise exception 'ASSERT warehouse stock private';end if;
 blocked:=false;begin perform public.receive_stock(loc,null,null,null,jsonb_build_array(jsonb_build_object('product_id',target,'quantity',100,'expiry_date',current_date+365)));exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT supplier receiving stays denied';end if;
 blocked:=false;begin perform public.process_stock_transfer(t,'cancel','Not authorised');exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT receiver cannot cancel';end if;
 perform public.process_stock_transfer(t,'receive');perform public.process_stock_transfer(t,'receive');
 if (select quantity from public.stock where product_id=target)<>6 then raise exception 'ASSERT receiving increments once';end if;
 if (select received_by from public.stock_transfers where id=t)<>staff then raise exception 'ASSERT actual cashier recorded';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 if (select quantity from public.stock where product_id=p)<>6 then raise exception 'ASSERT source deducted only at dispatch';end if;
 select id,quantity into b,before_qty from public.stock_batches where product_id=target and expiry_date=current_date+365 order by id limit 1;
 perform public.correct_batch_expiry(b,current_date+400,current_date+365,before_qty,'Corrected label');
 blocked:=false;begin perform public.correct_batch_expiry(b,current_date+500,current_date+365,before_qty,'Stale request');exception when others then if sqlerrm<>'BATCH_CHANGED_REFRESH' then raise;end if;blocked:=true;end;
 if not blocked or (select quantity from public.stock where product_id=target)<>6 then raise exception 'ASSERT expiry correction concurrency and quantity';end if;
 if not exists(select 1 from public.audit_logs where action='stock.expiry_corrected' and entity_id=b) then raise exception 'ASSERT correction audited';end if;
 payload:=jsonb_build_array(jsonb_build_object('product_id',target,'quantity',1,'unit_price',10));
 sale:=public.complete_checkout(loc,payload,'[{"method":"CASH","amount":5},{"method":"CARD_EFT","amount":7,"confirmed":true}]',gen_random_uuid());
 if (select (snapshot->>'change')::numeric from public.sale_receipts where sale_id=sale)<>2 then raise exception 'ASSERT combined payment change';end if;
 if (select sum(amount) from public.sale_payments where sale_id=sale)<>10 then raise exception 'ASSERT combined settlement';end if;
 insert into public.customers(business_id,store_id,name) values(biz,loc,'Credit buyer') returning id into c;
 perform public.set_credit_limit(c,1000);
 sale:=public.complete_checkout(loc,payload,'[]',gen_random_uuid(),c,true);
 update public.customers set name='Renamed buyer' where id=c;
 if (select snapshot->>'customer_name' from public.sale_receipts where sale_id=sale)<>'Credit buyer' then raise exception 'ASSERT credit customer snapshot';end if;
 if (select snapshot->'items'->0 ? 'sku' from public.sale_receipts where sale_id=sale) then raise exception 'ASSERT SKU never customer receipt';end if;
 select id into line from public.goods_out_items where goods_out_id=sale;
 payload:=jsonb_build_array(jsonb_build_object('item_id',line,'quantity',1,'condition','GOOD','action','RETURN_TO_STOCK'));
 blocked:=false;begin perform public.submit_goods_return('sale',sale,payload,'Expired','Checked',gen_random_uuid());exception when others then if sqlerrm<>'EXPIRY_REQUIRED' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT expired reason requires date on server';end if;
 ret:=public.submit_goods_return('sale',sale,payload,'Unwanted','Sealed',gen_random_uuid());perform public.process_goods_return(ret,true);
 if (select undated_quantity from public.v_product_catalog where id=target)<>1 then raise exception 'ASSERT optional date kept undated';end if;
 if (select sellable_quantity>=quantity from public.v_product_catalog where id=target) then raise exception 'ASSERT undated return not sellable';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
