do $$
declare u uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); biz uuid; src uuid; dest uuid; another uuid; pid uuid; target uuid; mid uuid;
  t uuid; cancelled uuid; req uuid:=gen_random_uuid(); payload jsonb; res jsonb; q numeric; n int; blocked boolean;
begin
  insert into auth.users(id,email,raw_user_meta_data) values(u,'transfers-owner@test.invalid','{}'),(staff,'transfers-staff@test.invalid','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  set local role authenticated;
  res:=public.create_business('Transfer tests','Main'); biz:=(res->>'business_id')::uuid; dest:=(res->>'store_id')::uuid;
  src:=public.create_location(biz,'Warehouse','warehouse'); another:=public.create_location(biz,'Other','store');
  pid:=public.create_product(src,'Milk','SRC',null,null,10,15,0,0,'each',true);
  target:=public.create_product(dest,'Milk','DEST',null,null,10,15,0,0,'each',true);
  perform public.receive_stock(src,null,null,null,jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',10,'expiry_date','2028-01-01')));
  payload:=jsonb_build_array(jsonb_build_object('source_product_id',pid,'destination_product_id',target,'quantity',4));
  t:=public.create_stock_transfer(src,dest,payload,req,'Delivery');
  if t<>public.create_stock_transfer(src,dest,payload,req,'Delivery') then raise exception 'ASSERT idempotent transfer create'; end if;
  blocked:=false;
  begin perform public.process_stock_transfer(t,'receive'); exception when others then if sqlerrm<>'INVALID_TRANSFER_STATE' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT cannot receive draft'; end if;
  perform public.process_stock_transfer(t,'submit');
  select quantity into q from public.stock where product_id=pid and store_id=src;
  if q<>10 then raise exception 'ASSERT submit does not move stock'; end if;
  perform public.process_stock_transfer(t,'dispatch'); perform public.process_stock_transfer(t,'dispatch');
  select quantity into q from public.stock where product_id=pid and store_id=src;
  if q<>6 then raise exception 'ASSERT dispatch once'; end if;
  select quantity into q from public.stock where product_id=target and store_id=dest;
  if q<>0 then raise exception 'ASSERT stock in transit not saleable'; end if;
  perform public.process_stock_transfer(t,'receive'); perform public.process_stock_transfer(t,'receive');
  select quantity into q from public.stock where product_id=target and store_id=dest;
  if q<>4 then raise exception 'ASSERT receipt once'; end if;
  select sum(quantity) into q from public.stock_batches where product_id=target and store_id=dest and expiry_date='2028-01-01';
  if q<>4 then raise exception 'ASSERT expiry retained'; end if;
  select count(*) into n from public.stock_movements where reference_id=t and reference_table='stock_transfers';
  if n<>2 then raise exception 'ASSERT linked transfer movements'; end if;
  cancelled:=public.create_stock_transfer(src,dest,payload,gen_random_uuid());
  perform public.process_stock_transfer(cancelled,'submit'); perform public.process_stock_transfer(cancelled,'dispatch');
  blocked:=false;
  begin perform public.process_stock_transfer(cancelled,'cancel'); exception when others then if sqlerrm<>'REASON_REQUIRED' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT cancel reason'; end if;
  perform public.process_stock_transfer(cancelled,'cancel','Delivery rejected');
  select quantity into q from public.stock where product_id=pid and store_id=src;
  if q<>6 then raise exception 'ASSERT cancel restores source'; end if;
  if exists(select 1 from public.reconcile_stock(src) where diff<>0) or exists(select 1 from public.reconcile_stock(dest) where diff<>0) then raise exception 'ASSERT transfer reconciliation'; end if;
  t:=public.create_stock_transfer(src,dest,jsonb_build_array(jsonb_build_object('source_product_id',pid,'destination_product_id',target,'quantity',99)),gen_random_uuid());
  blocked:=false;
  begin perform public.process_stock_transfer(t,'submit'); exception when others then if sqlerrm<>'INSUFFICIENT_STOCK' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT shortage denied'; end if;
  reset role; mid:=public.add_member_by_email(biz,'transfers-staff@test.invalid','employee'); set local role authenticated;
  select count(*) into n from public.transfer_history(biz,p_status=>'RECEIVED',p_product=>'Milk');
  if n<>1 then raise exception 'ASSERT transfer status/product filter'; end if;
  perform public.set_member_locations(mid,array[dest]);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
  if exists(select 1 from public.stock_transfers) then raise exception 'ASSERT one-sided transfer hidden'; end if;
  if exists(select 1 from public.transfer_history(biz)) then raise exception 'ASSERT history RPC follows assignments'; end if;
  blocked:=false;
  begin perform public.create_stock_transfer(src,dest,payload,gen_random_uuid()); exception when others then if sqlerrm<>'FORBIDDEN' then raise; end if; blocked:=true; end;
  if not blocked then raise exception 'ASSERT unassigned transfer blocked'; end if;
  reset role; raise exception 'TESTS_PASSED';
end $$;
