do $$
declare u uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); biz uuid; shop uuid; shop2 uuid; usd_shop uuid; wh uuid; foreign_wh uuid; p uuid; p2 uuid; target uuid; other uuid; r jsonb; n int; blocked boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(u,'sync-owner@test.invalid','{}'),(employee,'sync-employee@test.invalid','{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 r:=public.create_business('Sync business','Shop');biz:=(r->>'business_id')::uuid;shop:=(r->>'store_id')::uuid;
 shop2:=public.create_location(biz,'Second shop','store');wh:=public.create_location(biz,'Warehouse','warehouse');
 p:=public.create_product(shop,'Preferred product','111',null,null,2,4,1,2,'each');
 p2:=public.create_product(shop2,'Other name','111',null,null,3,6,1,2,'each');
 reset role;update public.products set sku='SKU1' where id in(p,p2);set local role authenticated;
 perform public.receive_stock(shop,null,null,null,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',50)));
 r:=public.sync_warehouse_products(wh,shop,true);
 if (r->>'created')::int<>1 or jsonb_array_length(r->'errors')<>0 then raise exception 'ASSERT initial sync %',r;end if;
 select id into target from public.products where store_id=wh and sku='SKU1';
 if (select quantity from public.stock where product_id=target)<>0 or (select name from public.products where id=target)<>'Preferred product' then raise exception 'ASSERT preferred source and zero quantity';end if;
 perform public.receive_stock(wh,null,null,null,jsonb_build_array(jsonb_build_object('product_id',target,'quantity',7)));
 r:=public.sync_warehouse_products(wh,shop,true);
 if (r->>'created')::int<>0 or (r->>'updated')::int<>0 or (select quantity from public.stock where product_id=target)<>7 then raise exception 'ASSERT repeat is idempotent %',r;end if;
 reset role;update public.products set name='Renamed',sku='NEW-SKU',selling_price=5,description='Keep description' where id=p;set local role authenticated;
 r:=public.sync_warehouse_products(wh,shop,true);
 if (select count(*) from public.products where store_id=wh)<>1 or (select name from public.products where id=target)<>'Renamed' then raise exception 'ASSERT source identity persists %',r;end if;
 -- Template quantities never affect warehouse stock; omitted fields are preserved.
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('id',p,'name','Template name','quantity',999,'expiry_date','2030-01-01')));
 if (r->>'updated')::int<>1 or (select quantity from public.stock where product_id=target)<>7 or (select description from public.products where id=target)<>'Keep description' or (select count(*) from public.product_barcodes where product_id=target and is_active)<>1 then raise exception 'ASSERT template preserves stock and omitted details %',r;end if;
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('id',p,'name','Bad structure','unit','pack')));
 if r->'errors'->0->>'error'<>'STOCK_STRUCTURE_REQUIRES_REVIEW' or (select unit from public.products where id=target)<>'each' then raise exception 'ASSERT stock structure guard %',r;end if;
 other:=public.create_product(wh,'Distinct product','222',null,null,1,2,0,0,'each');
 reset role;update public.products set sku='OTHER' where id=other;set local role authenticated;
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('name','Collision','sku','NEW-SKU','barcode','222')));
 if r->'errors'->0->>'error'<>'CONFLICTING_PRODUCT_IDENTIFIERS' then raise exception 'ASSERT ambiguous match %',r;end if;
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('name','No identity')));
 if r->'errors'->0->>'error'<>'SKU_OR_BARCODE_REQUIRED' then raise exception 'ASSERT no name matching';end if;
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('name','New manual','sku','MANUAL','quantity',100)));
 if (r->>'created')::int<>1 or (select quantity from public.stock s join public.products p on p.id=s.product_id where p.store_id=wh and p.sku='MANUAL')<>0 then raise exception 'ASSERT new manual stock zero %',r;end if;
 reset role;alter table public.products disable trigger trg_products_touch;update public.products set updated_at=now()+interval '1 minute' where id=p2;alter table public.products enable trigger trg_products_touch;set local role authenticated;
 r:=public.sync_warehouse_products(wh,null,true);
 if (select name from public.products where id=target)<>'Other name' then raise exception 'ASSERT latest source priority %',r;end if;
 usd_shop:=public.create_location(biz,'USD shop','store');reset role;update public.stores set currency='USD' where id=usd_shop;set local role authenticated;
 perform public.create_product(usd_shop,'USD item','999',null,null,1,2);
 r:=public.sync_warehouse_products(wh,usd_shop,true);
 if r->'errors'->0->>'error'<>'CURRENCY_MISMATCH' then raise exception 'ASSERT currency guard %',r;end if;
 r:=public.create_business('Different business','Other business shop');foreign_wh:=(r->>'store_id')::uuid;
 other:=public.create_product(foreign_wh,'Foreign product','888',null,null,1,2);
 r:=public.import_warehouse_catalog(wh,jsonb_build_array(jsonb_build_object('id',other,'name','Foreign product')));
 if r->'errors'->0->>'error'<>'SOURCE_PRODUCT_NOT_IN_BUSINESS' then raise exception 'ASSERT cross-business source denied %',r;end if;
 r:=public.sync_warehouse_products(wh,shop,false);
 reset role;update public.products set name='Paused change' where id=p;
 perform app.run_warehouse_catalog_sync();
 if (select name from public.products where id=target)='Paused change' then raise exception 'ASSERT paused schedule skipped';end if;
 set local role authenticated;perform public.sync_warehouse_products(wh,shop,true);
 -- Private runner executes without a user JWT, but rechecks configured owner's permissions.
 reset role;
 perform set_config('request.jwt.claims','{}',true);perform app.run_warehouse_catalog_sync();
 if (select last_result ? 'error' from public.warehouse_sync_settings where warehouse_id=wh) then raise exception 'ASSERT scheduled sync without user session';end if;
 if (select quantity from public.stock where product_id=target)<>7 then raise exception 'ASSERT scheduled sync stock unchanged';end if;
 if not exists(select 1 from public.audit_logs where store_id=wh and action='warehouse.catalog_update') then raise exception 'ASSERT sync audit';end if;
 if has_function_privilege('authenticated','app.run_warehouse_catalog_sync()','execute') or has_function_privilege('anon','public.sync_warehouse_products(uuid,uuid,boolean)','execute') then raise exception 'ASSERT function grants';end if;
 update public.memberships set is_active=false where business_id=biz and user_id=u;
 perform app.run_warehouse_catalog_sync();
 if not (select last_result ? 'error' from public.warehouse_sync_settings where warehouse_id=wh) then raise exception 'ASSERT revoked owner stops scheduler';end if;
 update public.memberships set is_active=true where business_id=biz and user_id=u;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.sync_warehouse_products(wh,shop,true);exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;blocked:=true;end;
 if not blocked then raise exception 'ASSERT nonowner blocked';end if;
 if exists(select 1 from public.warehouse_sync_settings where warehouse_id=wh) then raise exception 'ASSERT settings privacy';end if;
 reset role;raise exception 'TESTS_PASSED';
end $$;
