export type OnlineSettings = {
  store_id: string;
  link_token: string;
  enabled: boolean;
  collection_enabled: boolean;
  delivery_enabled: boolean;
  pay_on_collection: boolean;
  delivery_fee: number;
  payment_instructions: string;
  reservation_hours: number;
  notifications_enabled: boolean;
  version: number;
};
export type Shop = {
  name: string;
  business: string;
  address: string;
  contact: string;
  currency: string;
  tax_percent: number;
  today: string;
  collection_enabled: boolean;
  delivery_enabled: boolean;
  pay_on_collection: boolean;
  delivery_fee: number;
  payment_instructions: string;
  reservation_hours: number;
};
export type OnlineProduct = {
  id: string;
  name: string;
  description: string;
  price: number;
  unit: string;
  image_url: string | null;
  variant_group: string | null;
  variant: string | null;
  available: boolean;
};
export type Catalog = {
  shop: Shop;
  products: OnlineProduct[];
  next: string | null;
};
export type OnlineOrder = {
  id: string;
  reference: string;
  customer: string;
  store: string;
  store_address: string;
  currency: string;
  date: string;
  fulfilment: "COLLECTION" | "DELIVERY";
  payment_option: string;
  payment_reference: string;
  payment_status: string;
  status: string;
  total: number;
  delivery_fee: number;
  tax_percent: number;
  expires_at: string;
  scheduled_date: string;
  invoice_number: string | null;
  delivery_number: string | null;
  courier_company: string | null;
  tracking_number: string | null;
  tracking_url: string | null;
  comments: string | null;
  cancellation_reason: string | null;
  payment_instructions: string;
  lines: {
    name: string;
    quantity: number;
    unit: string;
    price: number;
    total: number;
  }[];
  version: number;
  invoice_id: string | null;
};
