// Per-store child permissions. Parents and dependencies must also be enabled.
export const MODULE_FEATURES = [
  {
    key: "products_edit",
    label: "Add and edit product records",
    parent: "products",
    role: "employee",
    requires: [],
  },
  {
    key: "products_manage",
    label: "Edit products and stock configuration",
    parent: "products",
    role: "employee",
    requires: [],
  },
  {
    key: "stock_take_approve",
    label: "Approve and apply stock counts",
    parent: "stock_take",
    role: "employee",
    requires: [],
  },
  {
    key: "cash_up_manage",
    label: "Review cash-up and manage cash movements",
    parent: "cash_up",
    role: "employee",
    requires: [],
  },
  {
    key: "credit_manage",
    label: "Manage credit limits and account status",
    parent: "credit",
    role: "employee",
    requires: [],
  },
  {
    key: "credit_override",
    label: "Approve credit-limit overrides",
    parent: "credit",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_manage",
    label: "Correct invoices, cancel and issue adjustments",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "orders_approve",
    label: "Approve purchase orders and cancel delivery orders",
    parent: "orders",
    role: "employee",
    requires: [],
  },
  {
    key: "returns_manage",
    label: "Approve refunds and resolve quarantine",
    parent: "returns",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_in_cost",
    label: "Change receiving costs",
    parent: "goods_in",
    role: "employee",
    requires: [],
  },
  {
    key: "reports_financial",
    label: "View profit and invoice reconciliation",
    parent: "reports",
    role: "employee",
    requires: [],
  },
  {
    key: "settings_manage",
    label: "Edit location and notification settings",
    parent: "settings",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_approve",
    label: "Approve bulk stock count overrides",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_out_receipt_settings",
    label: "Change receipt printing preferences",
    parent: "goods_out",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_out_override",
    label: "Approve sale overrides",
    parent: "goods_out",
    role: "employee",
    requires: [],
  },
  {
    key: "check_stock_costs",
    label: "Show stock cost and margin summaries",
    parent: "check_stock",
    role: "employee",
    requires: [],
  },
  {
    key: "reports_delivery",
    label: "View Delivery Report",
    parent: "reports",
    role: "employee",
    requires: [],
  },
  {
    key: "reports_delivery_print",
    label: "Print Delivery Report",
    parent: "reports",
    role: "employee",
    requires: ["reports_delivery"],
  },
  {
    key: "reports_delivery_excel",
    label: "Export Delivery Report to Excel",
    parent: "reports",
    role: "employee",
    requires: ["reports_delivery"],
  },
  {
    key: "reports_delivery_pdf",
    label: "Export Delivery Report to PDF",
    parent: "reports",
    role: "employee",
    requires: ["reports_delivery"],
  },
  {
    key: "orders_deliveries",
    label: "Manage deliveries",
    parent: "orders",
    role: "employee",
    requires: ["orders_recent"],
  },
  {
    key: "goods_out_change_price",
    label: "Change selling price / discount",
    parent: "goods_out",
    role: "employee",
    requires: [],
  },
  {
    key: "warehouse_disable",
    label: "Disable Warehouse",
    parent: "warehouse",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_in_new_stock",
    label: "Receive New Stock / Supplier",
    parent: "goods_in",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_in_receive_transfer",
    label: "Receive Stock Transfer",
    parent: "goods_in",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_create",
    label: "Create Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_dispatch",
    label: "Dispatch Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_modify",
    label: "Submit / Cancel Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_view",
    label: "View Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "dashboard_goods_in",
    label: "Goods In",
    parent: "dashboard",
    role: "employee",
    requires: ["goods_in"],
  },
  {
    key: "dashboard_goods_out",
    label: "Goods Out",
    parent: "dashboard",
    role: "employee",
    requires: ["goods_out"],
  },
  {
    key: "dashboard_check_stock",
    label: "Check Stock",
    parent: "dashboard",
    role: "employee",
    requires: ["check_stock"],
  },
  {
    key: "dashboard_check_price",
    label: "Check Price",
    parent: "dashboard",
    role: "employee",
    requires: ["check_price"],
  },
  {
    key: "dashboard_adjust",
    label: "Adjust Stock",
    parent: "dashboard",
    role: "employee",
    requires: ["adjust"],
  },
  {
    key: "dashboard_credit",
    label: "Customers",
    parent: "dashboard",
    role: "employee",
    requires: ["credit"],
  },
  {
    key: "dashboard_locations",
    label: "All Business Locations",
    parent: "dashboard",
    role: "owner",
    requires: ["stores"],
  },
  {
    key: "dashboard_invoicing",
    label: "Invoicing",
    parent: "dashboard",
    role: "employee",
    requires: ["invoices_summary"],
  },
  {
    key: "dashboard_movements",
    label: "Recent Stock Movements",
    parent: "dashboard",
    role: "employee",
    requires: [],
  },
  {
    key: "orders_new",
    label: "New Order",
    parent: "orders",
    role: "employee",
    requires: [],
  },
  {
    key: "orders_recent",
    label: "Recent Orders",
    parent: "orders",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_create_quotes",
    label: "Create Quotes",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_view_quotes",
    label: "View All Quotes",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_create_from_order",
    label: "Create from Order",
    parent: "invoices",
    role: "employee",
    requires: ["orders_recent"],
  },
  {
    key: "invoices_view_invoices",
    label: "View Invoices",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_summary",
    label: "Invoicing",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_invoiced",
    label: "Invoiced",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_paid",
    label: "Paid / Allocated",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_outstanding",
    label: "Outstanding",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_overdue",
    label: "Overdue",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_credit_notes",
    label: "Credit Notes",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_month_to_date",
    label: "Invoiced This Month",
    parent: "invoices_summary",
    role: "employee",
    requires: [],
  },
] as const;
