// Per-store child permissions. Parents and dependencies must also be enabled.
export const MODULE_FEATURES = [
  {
    key: "goods_out_change_price",
    label: "Change selling price / discount",
    parent: "goods_out",
    role: "employee",
    requires: [],
  },
  {
    key: "warehouse_disable",
    label: "Disable Warehouse",
    parent: "warehouse",
    role: "manager",
    requires: [],
  },
  {
    key: "goods_in_new_stock",
    label: "Receive New Stock / Supplier",
    parent: "goods_in",
    role: "employee",
    requires: [],
  },
  {
    key: "goods_in_receive_transfer",
    label: "Receive Stock Transfer",
    parent: "goods_in",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_create",
    label: "Create Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_dispatch",
    label: "Dispatch Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_modify",
    label: "Submit / Cancel Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "operations_transfer_view",
    label: "View Transfers",
    parent: "operations",
    role: "employee",
    requires: [],
  },
  {
    key: "dashboard_goods_in",
    label: "Goods In",
    parent: "dashboard",
    role: "employee",
    requires: ["goods_in"],
  },
  {
    key: "dashboard_goods_out",
    label: "Goods Out",
    parent: "dashboard",
    role: "employee",
    requires: ["goods_out"],
  },
  {
    key: "dashboard_check_stock",
    label: "Check Stock",
    parent: "dashboard",
    role: "employee",
    requires: ["check_stock"],
  },
  {
    key: "dashboard_check_price",
    label: "Check Price",
    parent: "dashboard",
    role: "employee",
    requires: ["check_price"],
  },
  {
    key: "dashboard_adjust",
    label: "Adjust Stock",
    parent: "dashboard",
    role: "manager",
    requires: ["adjust"],
  },
  {
    key: "dashboard_credit",
    label: "Credit",
    parent: "dashboard",
    role: "employee",
    requires: ["credit"],
  },
  {
    key: "dashboard_locations",
    label: "All Business Locations",
    parent: "dashboard",
    role: "owner",
    requires: ["stores"],
  },
  {
    key: "dashboard_invoicing",
    label: "Invoicing",
    parent: "dashboard",
    role: "manager",
    requires: ["invoices_summary"],
  },
  {
    key: "dashboard_movements",
    label: "Recent Stock Movements",
    parent: "dashboard",
    role: "employee",
    requires: [],
  },
  {
    key: "orders_new",
    label: "New Order",
    parent: "orders",
    role: "employee",
    requires: [],
  },
  {
    key: "orders_recent",
    label: "Recent Orders",
    parent: "orders",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_create_quotes",
    label: "Create Quotes",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_view_quotes",
    label: "View All Quotes",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_create_from_order",
    label: "Create from Order",
    parent: "invoices",
    role: "employee",
    requires: ["orders_recent"],
  },
  {
    key: "invoices_view_invoices",
    label: "View Invoices",
    parent: "invoices",
    role: "employee",
    requires: [],
  },
  {
    key: "invoices_summary",
    label: "Invoicing",
    parent: "invoices",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_invoiced",
    label: "Invoiced",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_paid",
    label: "Paid / Allocated",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_outstanding",
    label: "Outstanding",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_overdue",
    label: "Overdue",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_credit_notes",
    label: "Credit Notes",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
  {
    key: "invoices_month_to_date",
    label: "Invoiced This Month",
    parent: "invoices_summary",
    role: "manager",
    requires: [],
  },
] as const;
