import Link from "next/link";
import {redirect} from "next/navigation";
import {getSession} from "@/lib/session";
import {createClient} from "@/lib/supabase/server";
import {PageHeader} from "@/components/shell/page-header";
import {ExportButton} from "@/features/reports/export-button";
import {Table,THead,TBody,TR,TH,TD} from "@/components/ui/table";
import {money} from "@/lib/format";
export default async function AgeingPage(){const session=await getSession("reports");if(!session?.activeStore)redirect("/onboarding");const store=session.activeStore;const db=await createClient();const {data,error}=await db.from("v_invoice_balances").select("*").eq("store_id",store.id).gt("outstanding",0).order("due_date").limit(1000);if(error)throw error;const asOf=new Date().getTime();const rows=(data??[]).map(i=>{const days=Math.max(0,Math.floor((asOf-new Date(`${i.due_date}T00:00:00+02:00`).getTime())/86400000));return{id:i.id,reference:i.reference,customer:i.customer_name,due:i.due_date,days,bucket:days===0?"Current":days<=30?"1–30 days":days<=60?"31–60 days":days<=90?"61–90 days":"90+ days",outstanding:Number(i.outstanding)};});return <><PageHeader title="Invoice Ageing" description="Unpaid invoice balances grouped by days past their due date." crumbs={[{label:"Reports",href:"/reports"},{label:"Ageing"}]} actions={<ExportButton rows={rows} columns={[{key:"reference",label:"Invoice"},{key:"customer",label:"Customer"},{key:"due",label:"Due date"},{key:"days",label:"Days overdue"},{key:"bucket",label:"Ageing"},{key:"outstanding",label:"Outstanding"}]} filename="invoice-ageing"/>}/>{rows.length===1000&&<p className="text-warning">Showing the oldest 1,000 outstanding invoices.</p>}<Table><THead><TR><TH>Invoice</TH><TH>Customer</TH><TH>Due</TH><TH>Age</TH><TH>Outstanding</TH></TR></THead><TBody>{rows.map(r=><TR key={r.id}><TD><Link className="text-accent" href={`/invoices/${r.id}`}>{r.reference}</Link></TD><TD>{r.customer}</TD><TD>{r.due}</TD><TD>{r.bucket}</TD><TD>{money(r.outstanding,store.currency)}</TD></TR>)}</TBody></Table></>;}
