import {redirect} from "next/navigation";
import {getSession} from "@/lib/session";
import {createClient} from "@/lib/supabase/server";
import {PageHeader} from "@/components/shell/page-header";
import {ExportButton} from "@/features/reports/export-button";
import {money} from "@/lib/format";
export default async function ReconciliationPage({searchParams}:{searchParams:Promise<{month?:string}>}){
  const {month:input}=await searchParams;const month=input&&/^\d{4}-(0[1-9]|1[0-2])$/.test(input)?input:new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit"}).format(new Date());
  const session=await getSession();if(!session?.activeStore)redirect("/onboarding");const store=session.activeStore;if(store.role==="employee")redirect("/reports");const db=await createClient();const {data,error}=await db.rpc("invoice_monthly_reconciliation",{p_store:store.id,p_month:`${month}-01`});if(error)throw error;const v=data as Record<string,number>;
  const labels:Record<string,string>={opening:"Opening invoice balance",invoiced:"Invoices issued",debits:"Debit notes / credit allocated out",credit_notes:"Credit notes",voided:"Voided invoices",cash_received:"Cash received",card_received:"Card/EFT received",store_credit_received:"Store credit allocated in",closing:"Closing invoice balance",refunds:"Refunds paid (separate cash flow)",customer_ledger_balance:"Customer ledger balance (all activity)"};const rows=Object.entries(labels).map(([key,label])=>({label,amount:Number(v[key]??0)}));
  return <><PageHeader title="Monthly Reconciliation" description="Reconcile invoice entries for a calendar month in South African time, with refunds shown separately." crumbs={[{label:"Reports",href:"/reports"},{label:"Reconciliation"}]} actions={<ExportButton rows={rows} columns={[{key:"label",label:"Measure"},{key:"amount",label:"Amount"}]} filename={`reconciliation-${month}`}/>}/><form className="mb-5 flex gap-3"><input aria-label="Reconciliation month" name="month" type="month" defaultValue={month} className="rounded border border-border bg-input px-3 py-2"/><button className="rounded bg-primary px-4">Show month</button></form><dl className="max-w-2xl rounded-lg border border-border bg-surface p-5">{rows.map(r=><div key={r.label} className="flex justify-between gap-4 border-b border-border py-3"><dt>{r.label}</dt><dd className="font-semibold tabular-nums">{money(r.amount,store.currency)}</dd></div>)}</dl><p className="mt-4 max-w-2xl text-sm text-muted">Closing = opening + invoices + debit notes − credit notes − voids − payments (including allocated store credit). The customer ledger also includes checkout credit, refunds and other account entries.</p></>;
}
