"use client";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {createClient} from "@/lib/supabase/client";
import {useStore} from "@/lib/store-context";
import {useBillingAction} from "@/features/billing/use-billing-action";
import {Button} from "@/components/ui/button";
import {dateTime} from "@/lib/format";
const kinds=[{key:"OUT_OF_STOCK",label:"Out of stock",schedule:"Daily when products are unavailable"},{key:"UPCOMING_EXPIRY",label:"Upcoming expiry",schedule:"Daily for batches expiring in 30 days"},{key:"STOCK_TAKE_COMPLETED",label:"Stock take completed",schedule:"Hourly check for newly completed counts"},{key:"LOW_STOCK",label:"Low stock",schedule:"Daily when products need replenishment"},{key:"WEEKLY_PROFIT",label:"Weekly profit",schedule:"Monday, covering the previous week"},{key:"OVERDUE_INVOICES",label:"Overdue invoices",schedule:"Daily when unpaid invoices are overdue"}];
type Preference={id:string;kind:string;enabled:boolean;delivery_hour:number};
export function NotificationPreferences({initial}:{initial:Preference[]}){
  const {store,user,can}=useStore();const {online,busy,run}=useBillingAction();const [settings,setSettings]=useState(()=>Object.fromEntries(kinds.map(k=>[k.key,{enabled:initial.find(p=>p.kind===k.key)?.enabled??false,hour:initial.find(p=>p.kind===k.key)?.delivery_hour??8}])));
  const history=useQuery({queryKey:["billing","notification-history",store.id],enabled:can("manager"),queryFn:async()=>{const db=createClient();const prefs=await db.from("notification_preferences").select("id").eq("store_id",store.id);if(prefs.error)throw prefs.error;if(!prefs.data?.length)return[];const {data,error}=await db.from("notification_deliveries").select("*").in("preference_id",prefs.data.map(p=>p.id)).order("created_at",{ascending:false}).limit(10);if(error)throw error;return data;}});
  if(!can("manager"))return null;
  return <section className="mt-6 max-w-3xl space-y-4 rounded-lg border border-border bg-surface p-5"><h2 className="font-semibold">Notification emails</h2><p className="text-sm text-muted">Send to your account email: {user.email}. Schedules use South African time. Emails require the deployed notification worker and delivery service.</p>{kinds.map(k=><div key={k.key} className="flex flex-wrap items-center gap-3 border-b border-border py-3"><label className="flex flex-1 items-start gap-2"><input type="checkbox" className="mt-1" checked={settings[k.key].enabled} onChange={e=>setSettings(old=>({...old,[k.key]:{...old[k.key],enabled:e.target.checked}}))}/><span><span className="block text-sm font-medium">{k.label}</span><span className="text-xs text-muted">{k.schedule}</span></span></label>{k.key!=="STOCK_TAKE_COMPLETED"&&<select aria-label={`${k.label} delivery hour`} className="h-9 rounded border border-border bg-input px-2" value={settings[k.key].hour} onChange={e=>setSettings(old=>({...old,[k.key]:{...old[k.key],hour:Number(e.target.value)}}))}>{Array.from({length:24},(_,hour)=><option key={hour} value={hour}>{String(hour).padStart(2,"0")}:00</option>)}</select>}<Button size="sm" variant="secondary" disabled={!online||busy} onClick={()=>run(()=>createClient().rpc("set_notification_preference",{p_store:store.id,p_kind:k.key,p_enabled:settings[k.key].enabled,p_hour:settings[k.key].hour}),`${k.label} preference saved`)}>Save</Button></div>)}<h3 className="text-sm font-semibold">Recent delivery checks</h3>{history.error&&<p role="alert">Could not load delivery history.</p>}{history.data?.map(d=><p key={d.id} className="text-xs text-muted">{dateTime(d.created_at)} · {d.state} · {d.error??(d.state==="SKIPPED"?"Nothing required an email":"")}</p>)}</section>;
}
