// @vitest-environment node
import { expect,it } from "vitest";
import sharp from "sharp";
import ExcelJS from "exceljs";
import { decodeDocumentLogo,logoSize } from "../../supabase/functions/_shared/document-logo";
import { reportPdf,reportXlsx,reportCsv } from "@/features/reports/export-data";
import { importTemplate,parseImport } from "@/features/imports/import-format";
import {createStockTakeWorkbook,readStockTakeWorkbook} from "@/features/stock-take/excel";
async function logo(){return decodeDocumentLogo(await sharp({create:{width:240,height:80,channels:4,background:'#e60849'}}).png().toBuffer());}
it("rejects invalid or oversized image dimensions and preserves aspect ratio",async()=>{const image=await logo();expect(logoSize(image,45,24)).toEqual({width:45,height:15});expect(()=>decodeDocumentLogo(new Uint8Array(25))).toThrow();const bytes=await sharp({create:{width:1025,height:1,channels:4,background:'#fff'}}).png().toBuffer();expect(()=>decodeDocumentLogo(bytes)).toThrow();});
it("keeps report data below an embedded logo and leaves CSV machine-readable",async()=>{const data={title:'Branded report',logo:await logo(),columns:[{key:'name',label:'Name'}],rows:[{name:'Item'}]};const book=new ExcelJS.Workbook();await book.xlsx.load(await reportXlsx(data));const sheet=book.getWorksheet('Report')!;expect(sheet.getImages()).toHaveLength(1);expect(sheet.getRow(1).height).toBe(80);expect(sheet.getCell('A6').value).toBe('Item');expect(reportCsv(data)).toBe('\ufeffName\r\nItem');const pdf=Buffer.from(await reportPdf({...data,rows:Array.from({length:180},(_,n)=>({name:`Item ${n}`}))})).toString('latin1');expect(pdf).toContain('/Subtype /Image');expect((pdf.match(/\/Type \/Page\b/g)??[]).length).toBeGreaterThan(1);});
it("round-trips branded import templates without treating the logo row as data",async()=>{const blob=await importTemplate('customers',[{name:'Branded customer',email:'buyer@example.test'}],await logo());expect(await parseImport('customers',await blob.arrayBuffer())).toEqual([{name:'Branded customer',email:'buyer@example.test'}]);});
it("round-trips branded stock counts with unchanged identities",async()=>{const store='00000000-0000-4000-8000-000000000001',take='00000000-0000-4000-8000-000000000002',item='00000000-0000-4000-8000-000000000003';const bytes=await createStockTakeWorkbook({export_id:'00000000-0000-4000-8000-000000000004',store_id:store,stock_take_id:take,store_name:'Shop',items:[{id:item,name:'Soap',sku:'SOAP',unit:'each',quantity:4}]},await logo());const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);const sheet=book.getWorksheet('Stock Take')!;expect(sheet.getImages()).toHaveLength(1);sheet.getCell('F3').value=5;const result=await readStockTakeWorkbook(new Uint8Array(await book.xlsx.writeBuffer()).buffer,store,take);expect(result.rows).toEqual([{item_id:item,quantity:5,same:false,expiry:null}]);});
