import { beforeEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SaleReceiptPrompt } from "@/features/goods-out/sale-receipt-prompt";
const m = vi.hoisted(() => ({ rpc: vi.fn(), done: vi.fn(), print:vi.fn(), copies:false }));
vi.mock("@/lib/print-document",()=>({printDocument:m.print}));
vi.mock("@/lib/supabase/client", () => ({ createClient: () => ({rpc:m.rpc,from:(table:string)=>({select:()=>({eq:()=>({single:async()=>({data:{reference:"POS-20261004-001",store_id:"s"},error:null}),maybeSingle:async()=>({data:table==="receipt_preferences"?{second_copy:m.copies,delay_seconds:0}:null,error:null})})})})}) }));
beforeEach(() => {cleanup();vi.restoreAllMocks();vi.clearAllMocks();m.copies=false;m.rpc.mockResolvedValue({error:null});m.print.mockResolvedValue(undefined);});
function show(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><SaleReceiptPrompt id="sale-1" total={50} currency="ZAR" onDone={m.done}/></QueryClientProvider>);}
it("requires an explicit receipt choice and does not dismiss on Escape",async()=>{show();await screen.findByText("POS-20261004-001");expect(screen.queryByRole("button",{name:"Close"})).toBeNull();fireEvent.keyDown(screen.getByRole("dialog"),{key:"Escape"});expect(m.done).not.toHaveBeenCalled();});
it("prints in place once and waits for the dialog to close",async()=>{let finish!:()=>void;m.print.mockImplementation(()=>new Promise<void>(resolve=>{finish=resolve}));const open=vi.spyOn(window,"open");show();await screen.findByText("POS-20261004-001");fireEvent.click(screen.getByRole("button",{name:"Print Receipt"}));fireEvent.click(screen.getByRole("button",{name:"Print Receipt"}));await waitFor(()=>expect(m.print).toHaveBeenCalledExactlyOnceWith("/goods-out/sale-1/receipt"));expect(open).not.toHaveBeenCalled();expect(m.done).not.toHaveBeenCalled();finish();await waitFor(()=>expect(m.done).toHaveBeenCalledOnce());});
it("keeps the saved sale and allows printing to be retried",async()=>{m.print.mockRejectedValueOnce(new Error("failed"));show();await screen.findByText("POS-20261004-001");fireEvent.click(screen.getByRole("button",{name:"Print Receipt"}));await screen.findByRole("alert");expect(m.done).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Print Receipt"}));await waitFor(()=>expect(m.done).toHaveBeenCalledOnce());});
it("prints the configured second copy",async()=>{m.copies=true;show();await screen.findByText("POS-20261004-001");fireEvent.click(screen.getByRole("button",{name:"Print Receipt"}));await waitFor(()=>expect(m.done).toHaveBeenCalledOnce());expect(m.print).toHaveBeenCalledTimes(2);expect(m.rpc).toHaveBeenNthCalledWith(2,"record_receipt_print",{p_sale:"sale-1",p_action:"COPY_REQUESTED"});});
it("records declining once before closing",async()=>{show();fireEvent.click(screen.getByRole("button",{name:"Don’t Print"}));fireEvent.click(screen.getByRole("button",{name:"Don’t Print"}));await waitFor(()=>expect(m.done).toHaveBeenCalledOnce());expect(m.rpc).toHaveBeenCalledExactlyOnceWith("record_receipt_print",{p_sale:"sale-1",p_action:"DECLINED"});});
it("retains the saved sale when recording the choice fails",async()=>{m.rpc.mockRejectedValueOnce(new Error("offline"));show();fireEvent.click(screen.getByRole("button",{name:"Don’t Print"}));await screen.findByRole("alert");expect(m.done).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Don’t Print"}));await waitFor(()=>expect(m.done).toHaveBeenCalledOnce());});
